# This file has been generated by node2nix 1.11.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@alcalzone/ansi-tokenize-0.2.5" = {
      name = "_at_alcalzone_slash_ansi-tokenize";
      packageName = "@alcalzone/ansi-tokenize";
      version = "0.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@alcalzone/ansi-tokenize/-/ansi-tokenize-0.2.5.tgz";
        sha512 = "3NX/MpTdroi0aKz134A6RC2Gb2iXVECN4QaAXnvCIxxIm3C3AVB1mkUe8NaaiyvOpDfsrqWhYtj+Q6a62RrTsw==";
      };
    };
    "@babel/helper-string-parser-7.27.1" = {
      name = "_at_babel_slash_helper-string-parser";
      packageName = "@babel/helper-string-parser";
      version = "7.27.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-string-parser/-/helper-string-parser-7.27.1.tgz";
        sha512 = "qMlSxKbpRlAridDExk92nSobyDdpPijUq2DW6oDnUqd0iOGxmQjyqhMIihI9+zv4LPyZdRje2cavWPbCbWm3eA==";
      };
    };
    "@babel/helper-validator-identifier-7.28.5" = {
      name = "_at_babel_slash_helper-validator-identifier";
      packageName = "@babel/helper-validator-identifier";
      version = "7.28.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-validator-identifier/-/helper-validator-identifier-7.28.5.tgz";
        sha512 = "qSs4ifwzKJSV39ucNjsvc6WVHs6b7S03sOh2OcHF9UHfVPqWWALUsNUVzhSBiItjRZoLHx7nIarVjqKVusUZ1Q==";
      };
    };
    "@babel/parser-7.29.2" = {
      name = "_at_babel_slash_parser";
      packageName = "@babel/parser";
      version = "7.29.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/parser/-/parser-7.29.2.tgz";
        sha512 = "4GgRzy/+fsBa72/RZVJmGKPmZu9Byn8o4MoLpmNe1m8ZfYnz5emHLQz3U4gLud6Zwl0RZIcgiLD7Uq7ySFuDLA==";
      };
    };
    "@babel/types-7.29.0" = {
      name = "_at_babel_slash_types";
      packageName = "@babel/types";
      version = "7.29.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/types/-/types-7.29.0.tgz";
        sha512 = "LwdZHpScM4Qz8Xw2iKSzS+cfglZzJGvofQICy7W7v4caru4EaAmyUuO6BGrbyQ2mYV11W0U8j5mBhd14dd3B0A==";
      };
    };
    "@emmetio/abbreviation-2.3.3" = {
      name = "_at_emmetio_slash_abbreviation";
      packageName = "@emmetio/abbreviation";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emmetio/abbreviation/-/abbreviation-2.3.3.tgz";
        sha512 = "mgv58UrU3rh4YgbE/TzgLQwJ3pFsHHhCLqY20aJq+9comytTXUDNGG/SMtSeMJdkpxgXSXunBGLD8Boka3JyVA==";
      };
    };
    "@emmetio/css-abbreviation-2.1.8" = {
      name = "_at_emmetio_slash_css-abbreviation";
      packageName = "@emmetio/css-abbreviation";
      version = "2.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emmetio/css-abbreviation/-/css-abbreviation-2.1.8.tgz";
        sha512 = "s9yjhJ6saOO/uk1V74eifykk2CBYi01STTK3WlXWGOepyKa23ymJ053+DNQjpFcy1ingpaO7AxCcwLvHFY9tuw==";
      };
    };
    "@emmetio/css-parser-0.4.1" = {
      name = "_at_emmetio_slash_css-parser";
      packageName = "@emmetio/css-parser";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emmetio/css-parser/-/css-parser-0.4.1.tgz";
        sha512 = "2bC6m0MV/voF4CTZiAbG5MWKbq5EBmDPKu9Sb7s7nVcEzNQlrZP6mFFFlIaISM8X6514H9shWMme1fCm8cWAfQ==";
      };
    };
    "@emmetio/html-matcher-1.3.0" = {
      name = "_at_emmetio_slash_html-matcher";
      packageName = "@emmetio/html-matcher";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emmetio/html-matcher/-/html-matcher-1.3.0.tgz";
        sha512 = "NTbsvppE5eVyBMuyGfVu2CRrLvo7J4YHb6t9sBFLyY03WYhXET37qA4zOYUjBWFCRHO7pS1B9khERtY0f5JXPQ==";
      };
    };
    "@emmetio/scanner-1.0.4" = {
      name = "_at_emmetio_slash_scanner";
      packageName = "@emmetio/scanner";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emmetio/scanner/-/scanner-1.0.4.tgz";
        sha512 = "IqRuJtQff7YHHBk4G8YZ45uB9BaAGcwQeVzgj/zj8/UdOhtQpEIupUhSk8dys6spFIWVZVeK20CzGEnqR5SbqA==";
      };
    };
    "@emmetio/stream-reader-2.2.0" = {
      name = "_at_emmetio_slash_stream-reader";
      packageName = "@emmetio/stream-reader";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emmetio/stream-reader/-/stream-reader-2.2.0.tgz";
        sha512 = "fXVXEyFA5Yv3M3n8sUGT7+fvecGrZP4k6FnWWMSZVQf69kAq0LLpaBQLGcPR30m3zMmKYhECP4k/ZkzvhEW5kw==";
      };
    };
    "@emmetio/stream-reader-utils-0.1.0" = {
      name = "_at_emmetio_slash_stream-reader-utils";
      packageName = "@emmetio/stream-reader-utils";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emmetio/stream-reader-utils/-/stream-reader-utils-0.1.0.tgz";
        sha512 = "ZsZ2I9Vzso3Ho/pjZFsmmZ++FWeEd/txqybHTm4OgaZzdS8V9V/YYWQwg5TC38Z7uLWUV1vavpLLbjJtKubR1A==";
      };
    };
    "@hono/node-server-1.19.14" = {
      name = "_at_hono_slash_node-server";
      packageName = "@hono/node-server";
      version = "1.19.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hono/node-server/-/node-server-1.19.14.tgz";
        sha512 = "GwtvgtXxnWsucXvbQXkRgqksiH2Qed37H9xHZocE5sA3N8O8O8/8FA3uclQXxXVzc9XBZuEOMK7+r02FmSpHtw==";
      };
    };
    "@hono/zod-validator-0.7.6" = {
      name = "_at_hono_slash_zod-validator";
      packageName = "@hono/zod-validator";
      version = "0.7.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hono/zod-validator/-/zod-validator-0.7.6.tgz";
        sha512 = "Io1B6d011Gj1KknV4rXYz4le5+5EubcWEU/speUjuw9XMMIaP3n78yXLhjd2A3PXaXaUwEAluOiAyLqhBEJgsw==";
      };
    };
    "@johnsoncodehk/pug-beautify-0.2.2" = {
      name = "_at_johnsoncodehk_slash_pug-beautify";
      packageName = "@johnsoncodehk/pug-beautify";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@johnsoncodehk/pug-beautify/-/pug-beautify-0.2.2.tgz";
        sha512 = "qqNS/YD0Nck5wtQLCPHAfGVgWbbGafxSPjNh0ekYPFSNNqnDH2kamnduzYly8IiADmeVx/MfAE1njMEjVeHTMA==";
      };
    };
    "@sec-ant/readable-stream-0.4.1" = {
      name = "_at_sec-ant_slash_readable-stream";
      packageName = "@sec-ant/readable-stream";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sec-ant/readable-stream/-/readable-stream-0.4.1.tgz";
        sha512 = "831qok9r2t8AlxLko40y2ebgSDhenenCatLVeW/uBtnHPyhHOvG0C7TvfgecV+wHzIm5KUICgzmVpWS+IMEAeg==";
      };
    };
    "@sindresorhus/merge-streams-4.0.0" = {
      name = "_at_sindresorhus_slash_merge-streams";
      packageName = "@sindresorhus/merge-streams";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sindresorhus/merge-streams/-/merge-streams-4.0.0.tgz";
        sha512 = "tlqY9xq5ukxTUZBmoOp+m61cqwQD5pHJtFY3Mn8CA8ps6yghLH/Hw8UPdqg4OLmFW3IFlcXnQNmo/dh8HzXYIQ==";
      };
    };
    "@standard-schema/spec-1.1.0" = {
      name = "_at_standard-schema_slash_spec";
      packageName = "@standard-schema/spec";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@standard-schema/spec/-/spec-1.1.0.tgz";
        sha512 = "l2aFy5jALhniG5HgqrD6jXLi/rUWrKvqN/qJx6yoJsgKhblVd+iqqU4RCXavm/jPityDo5TCvKMnpjKnOriy0w==";
      };
    };
    "@volar/language-core-2.4.28" = {
      name = "_at_volar_slash_language-core";
      packageName = "@volar/language-core";
      version = "2.4.28";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/language-core/-/language-core-2.4.28.tgz";
        sha512 = "w4qhIJ8ZSitgLAkVay6AbcnC7gP3glYM3fYwKV3srj8m494E3xtrCv6E+bWviiK/8hs6e6t1ij1s2Endql7vzQ==";
      };
    };
    "@volar/language-server-2.4.28" = {
      name = "_at_volar_slash_language-server";
      packageName = "@volar/language-server";
      version = "2.4.28";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/language-server/-/language-server-2.4.28.tgz";
        sha512 = "NqcLnE5gERKuS4PUFwlhMxf6vqYo7hXtbMFbViXcbVkbZ905AIVWhnSo0ZNBC2V127H1/2zP7RvVOVnyITFfBw==";
      };
    };
    "@volar/language-service-2.4.28" = {
      name = "_at_volar_slash_language-service";
      packageName = "@volar/language-service";
      version = "2.4.28";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/language-service/-/language-service-2.4.28.tgz";
        sha512 = "Rh/wYCZJrI5vCwMk9xyw/Z+MsWxlJY1rmMZPsxUoJKfzIRjS/NF1NmnuEcrMbEVGja00aVpCsInJfixQTMdvLw==";
      };
    };
    "@volar/source-map-2.4.28" = {
      name = "_at_volar_slash_source-map";
      packageName = "@volar/source-map";
      version = "2.4.28";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/source-map/-/source-map-2.4.28.tgz";
        sha512 = "yX2BDBqJkRXfKw8my8VarTyjv48QwxdJtvRgUpNE5erCsgEUdI2DsLbpa+rOQVAJYshY99szEcRDmyHbF10ggQ==";
      };
    };
    "@volar/typescript-2.4.28" = {
      name = "_at_volar_slash_typescript";
      packageName = "@volar/typescript";
      version = "2.4.28";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/typescript/-/typescript-2.4.28.tgz";
        sha512 = "Ja6yvWrbis2QtN4ClAKreeUZPVYMARDYZl9LMEv1iQ1QdepB6wn0jTRxA9MftYmYa4DQ4k/DaSZpFPUfxl8giw==";
      };
    };
    "@vscode/emmet-helper-2.11.0" = {
      name = "_at_vscode_slash_emmet-helper";
      packageName = "@vscode/emmet-helper";
      version = "2.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vscode/emmet-helper/-/emmet-helper-2.11.0.tgz";
        sha512 = "QLxjQR3imPZPQltfbWRnHU6JecWTF1QSWhx3GAKQpslx7y3Dp6sIIXhKjiUJ/BR9FX8PVthjr9PD6pNwOJfAzw==";
      };
    };
    "@vscode/l10n-0.0.18" = {
      name = "_at_vscode_slash_l10n";
      packageName = "@vscode/l10n";
      version = "0.0.18";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vscode/l10n/-/l10n-0.0.18.tgz";
        sha512 = "KYSIHVmslkaCDyw013pphY+d7x1qV8IZupYfeIfzNA+nsaWHbn5uPuQRvdRFsa9zFzGeudPuoGoZ1Op4jrJXIQ==";
      };
    };
    "@vue/compiler-core-3.5.32" = {
      name = "_at_vue_slash_compiler-core";
      packageName = "@vue/compiler-core";
      version = "3.5.32";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/compiler-core/-/compiler-core-3.5.32.tgz";
        sha512 = "4x74Tbtqnda8s/NSD6e1Dr5p1c8HdMU5RWSjMSUzb8RTcUQqevDCxVAitcLBKT+ie3o0Dl9crc/S/opJM7qBGQ==";
      };
    };
    "@vue/compiler-dom-3.5.32" = {
      name = "_at_vue_slash_compiler-dom";
      packageName = "@vue/compiler-dom";
      version = "3.5.32";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/compiler-dom/-/compiler-dom-3.5.32.tgz";
        sha512 = "ybHAu70NtiEI1fvAUz3oXZqkUYEe5J98GjMDpTGl5iHb0T15wQYLR4wE3h9xfuTNA+Cm2f4czfe8B4s+CCH57Q==";
      };
    };
    "@vue/language-core-3.2.6" = {
      name = "_at_vue_slash_language-core";
      packageName = "@vue/language-core";
      version = "3.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/language-core/-/language-core-3.2.6.tgz";
        sha512 = "xYYYX3/aVup576tP/23sEUpgiEnujrENaoNRbaozC1/MA9I6EGFQRJb4xrt/MmUCAGlxTKL2RmT8JLTPqagCkg==";
      };
    };
    "@vue/language-plugin-pug-3.2.6" = {
      name = "_at_vue_slash_language-plugin-pug";
      packageName = "@vue/language-plugin-pug";
      version = "3.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/language-plugin-pug/-/language-plugin-pug-3.2.6.tgz";
        sha512 = "lYspwAkAYRvydsxm+2bRMfb88amjsCi0TAYpqgZprRT7V5O0vGc4bNbV9Zm4WzSPbcsUMXCSntxyDfj6CSEj3A==";
      };
    };
    "@vue/language-service-3.2.6" = {
      name = "_at_vue_slash_language-service";
      packageName = "@vue/language-service";
      version = "3.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/language-service/-/language-service-3.2.6.tgz";
        sha512 = "UlZrmbodqzHptmeD2D6tNu4Ot63gr1u19j17F6t+3QWmr+xPf6ynShaM1FTuISXibWIDIlByZsDDI72vvAix1g==";
      };
    };
    "@vue/shared-3.5.32" = {
      name = "_at_vue_slash_shared";
      packageName = "@vue/shared";
      version = "3.5.32";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/shared/-/shared-3.5.32.tgz";
        sha512 = "ksNyrmRQzWJJ8n3cRDuSF7zNNontuJg1YHnmWRJd2AMu8Ij2bqwiiri2lH5rHtYPZjj4STkNcgcmiQqlOjiYGg==";
      };
    };
    "@vue/typescript-plugin-3.2.6" = {
      name = "_at_vue_slash_typescript-plugin";
      packageName = "@vue/typescript-plugin";
      version = "3.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/typescript-plugin/-/typescript-plugin-3.2.6.tgz";
        sha512 = "D7DO3/MDrdRAxZSpZU8SFBgk4a3d1yk75eKbDqAg7eM/AgpL7ur+PEuwqnOQiwFGEdtrhuFhiqksUtnzJHiq+w==";
      };
    };
    "@xterm/addon-serialize-0.14.0" = {
      name = "_at_xterm_slash_addon-serialize";
      packageName = "@xterm/addon-serialize";
      version = "0.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@xterm/addon-serialize/-/addon-serialize-0.14.0.tgz";
        sha512 = "uteyTU1EkrQa2Ux6P/uFl2fzmXI46jy5uoQMKEOM0fKTyiW7cSn0WrFenHm5vO5uEXX/GpwW/FgILvv3r0WbkA==";
      };
    };
    "@xterm/headless-6.0.0" = {
      name = "_at_xterm_slash_headless";
      packageName = "@xterm/headless";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@xterm/headless/-/headless-6.0.0.tgz";
        sha512 = "5Yj1QINYCyzrZtf8OFIHi47iQtI+0qYFPHmouEfG8dHNxbZ9Tb9YGSuLcsEwj9Z+OL75GJqPyJbyoFer80a2Hw==";
      };
    };
    "acorn-7.4.1" = {
      name = "acorn";
      packageName = "acorn";
      version = "7.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-7.4.1.tgz";
        sha512 = "nQyp0o1/mNdbTO1PO6kHkwSrmgZ0MT/jCCpNiwbUjGoRN4dlBhqJtoQuCnEOKzgTVwg0ZWiCoQy6SxMebQVh8A==";
      };
    };
    "agent-base-7.1.4" = {
      name = "agent-base";
      packageName = "agent-base";
      version = "7.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/agent-base/-/agent-base-7.1.4.tgz";
        sha512 = "MnA+YT8fwfJPgBx3m60MNqakm30XOkyIoH1y6huTQvC0PwZG7ki8NacLBcrPbNoo8vEZy7Jpuk7+jMO+CUovTQ==";
      };
    };
    "alien-signals-3.1.2" = {
      name = "alien-signals";
      packageName = "alien-signals";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/alien-signals/-/alien-signals-3.1.2.tgz";
        sha512 = "d9dYqZTS90WLiU0I5c6DHj/HcKkF8ZyGN3G5x8wSbslulz70KOxaqCT0hQCo9KOyhVqzqGojvNdJXoTumZOtcw==";
      };
    };
    "ansi-escapes-7.3.0" = {
      name = "ansi-escapes";
      packageName = "ansi-escapes";
      version = "7.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-escapes/-/ansi-escapes-7.3.0.tgz";
        sha512 = "BvU8nYgGQBxcmMuEeUEmNTvrMVjJNSH7RgW24vXexN4Ven6qCvy4TntnvlnwnMLTVlcRQQdbRY8NKnaIoeWDNg==";
      };
    };
    "ansi-regex-6.2.2" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "6.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-6.2.2.tgz";
        sha512 = "Bq3SmSpyFHaWjPk8If9yc6svM8c56dB5BAtW4Qbw5jHTwwXXcTLoRMkpDJp6VL0XzlWaCHTXrkFURMYmD0sLqg==";
      };
    };
    "ansi-styles-6.2.3" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "6.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-6.2.3.tgz";
        sha512 = "4Dj6M28JB+oAH8kFkTLUo+a2jwOFkuqb3yucU0CANcRRUbxS0cP0nZYCGjcc3BNXwRIsUVmDGgzawme7zvJHvg==";
      };
    };
    "asn1.js-5.4.1" = {
      name = "asn1.js";
      packageName = "asn1.js";
      version = "5.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1.js/-/asn1.js-5.4.1.tgz";
        sha512 = "+I//4cYPccV8LdmBLiX8CYvf9Sp3vQsrqu2QNXRcrbiWvcx/UdlFiqUJJzxRQxgsZmvhXhn4cSKeSmoFjVdupA==";
      };
    };
    "async-function-1.0.0" = {
      name = "async-function";
      packageName = "async-function";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/async-function/-/async-function-1.0.0.tgz";
        sha512 = "hsU18Ae8CDTR6Kgu9DYf0EbCr/a5iGL0rytQDobUcdpYOKokk8LEjVphnXkDkgpi0wYVsqrXuP0bZxJaTqdgoA==";
      };
    };
    "async-generator-function-1.0.0" = {
      name = "async-generator-function";
      packageName = "async-generator-function";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/async-generator-function/-/async-generator-function-1.0.0.tgz";
        sha512 = "+NAXNqgCrB95ya4Sr66i1CL2hqLVckAk7xwRYWdcm39/ELQ6YNn1aw5r0bdQtqNZgQpEWzc5yc/igXc7aL5SLA==";
      };
    };
    "auto-bind-5.0.1" = {
      name = "auto-bind";
      packageName = "auto-bind";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/auto-bind/-/auto-bind-5.0.1.tgz";
        sha512 = "ooviqdwwgfIfNmDwo94wlshcdzfO64XV0Cg6oDsDYBJfITDz1EngD2z7DkbvCWn+XIMsIqW27sEVF6qcpJrRcg==";
      };
    };
    "bn.js-4.12.3" = {
      name = "bn.js";
      packageName = "bn.js";
      version = "4.12.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/bn.js/-/bn.js-4.12.3.tgz";
        sha512 = "fGTi3gxV/23FTYdAoUtLYp6qySe2KE3teyZitipKNRuVYcBkoP/bB3guXN/XVKUe9mxCHXnc9C4ocyz8OmgN0g==";
      };
    };
    "buffer-equal-constant-time-1.0.1" = {
      name = "buffer-equal-constant-time";
      packageName = "buffer-equal-constant-time";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-equal-constant-time/-/buffer-equal-constant-time-1.0.1.tgz";
        sha512 = "zRpUiDwd/xk6ADqPMATG8vc9VPrkck7T07OIx0gnjmJAnHnTVXNQG3vfvWNuiZIkwu9KrKdA1iJKfsfTVxE6NA==";
      };
    };
    "call-bind-apply-helpers-1.0.2" = {
      name = "call-bind-apply-helpers";
      packageName = "call-bind-apply-helpers";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/call-bind-apply-helpers/-/call-bind-apply-helpers-1.0.2.tgz";
        sha512 = "Sp1ablJ0ivDkSzjcaJdxEunN5/XvksFJ2sMBFfq6x0ryhQV/2b/KwFe21cMpmHtPOSij8K99/wSfoEuTObmuMQ==";
      };
    };
    "call-bound-1.0.4" = {
      name = "call-bound";
      packageName = "call-bound";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/call-bound/-/call-bound-1.0.4.tgz";
        sha512 = "+ys997U96po4Kx/ABpBCqhA9EuxJaQWDQg7295H4hBphv3IZg0boBKuwYpt4YXp6MZ5AmZQnU/tyMTlRpaSejg==";
      };
    };
    "chalk-5.6.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "5.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-5.6.2.tgz";
        sha512 = "7NzBL0rN6fMUW+f7A6Io4h40qQlG+xGmtMxfbnH/K7TAtt8JQWVQK+6g0UXKMeVJoyV5EkkNsErQ8pVD3bLHbA==";
      };
    };
    "character-parser-2.2.0" = {
      name = "character-parser";
      packageName = "character-parser";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/character-parser/-/character-parser-2.2.0.tgz";
        sha512 = "+UqJQjFEFaTAs3bNsF2j2kEN1baG/zghZbdqoYEDxGZtJo9LBzl1A+m0D4n3qKx8N2FNv8/Xp6yV9mQmBuptaw==";
      };
    };
    "cli-boxes-3.0.0" = {
      name = "cli-boxes";
      packageName = "cli-boxes";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-boxes/-/cli-boxes-3.0.0.tgz";
        sha512 = "/lzGpEWL/8PfI0BmBOPRwp0c/wFNX1RdUML3jK/RcSBA9T8mZDdQpqYBKtCFTOfQbwPqWEOpjqW+Fnayc0969g==";
      };
    };
    "cli-cursor-4.0.0" = {
      name = "cli-cursor";
      packageName = "cli-cursor";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-cursor/-/cli-cursor-4.0.0.tgz";
        sha512 = "VGtlMu3x/4DOtIUwEkRezxUZ2lBacNJCHash0N0WeZDBS+7Ux1dm3XWAgWYxLJFMMdOeXMHXorshEFhbMSGelg==";
      };
    };
    "cli-truncate-5.2.0" = {
      name = "cli-truncate";
      packageName = "cli-truncate";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-truncate/-/cli-truncate-5.2.0.tgz";
        sha512 = "xRwvIOMGrfOAnM1JYtqQImuaNtDEv9v6oIYAs4LIHwTiKee8uwvIi363igssOC0O5U04i4AlENs79LQLu9tEMw==";
      };
    };
    "code-excerpt-4.0.0" = {
      name = "code-excerpt";
      packageName = "code-excerpt";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/code-excerpt/-/code-excerpt-4.0.0.tgz";
        sha512 = "xxodCmBen3iy2i0WtAK8FlFNrRzjUqjRsMfho58xT/wvZU1YTM3fCnRjcy1gJPMepaRlgm/0e6w8SpWHpn3/cA==";
      };
    };
    "convert-to-spaces-2.0.1" = {
      name = "convert-to-spaces";
      packageName = "convert-to-spaces";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/convert-to-spaces/-/convert-to-spaces-2.0.1.tgz";
        sha512 = "rcQ1bsQO9799wq24uE5AM2tAILy4gXGIK/njFWcVQkGNZ96edlpY+A7bjwvzjYvLDyzmG1MmMLZhpcsb+klNMQ==";
      };
    };
    "cross-spawn-7.0.6" = {
      name = "cross-spawn";
      packageName = "cross-spawn";
      version = "7.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-7.0.6.tgz";
        sha512 = "uV2QOWP2nWzsy2aMp8aRibhi9dlzF5Hgh5SHaB9OiTGEyDTiJJyx0uy51QXdyWbtAHNua4XJzUKca3OzKUd3vA==";
      };
    };
    "debug-4.4.3" = {
      name = "debug";
      packageName = "debug";
      version = "4.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.4.3.tgz";
        sha512 = "RGwwWnwQvkVfavKVt22FGLw+xYSdzARwm0ru6DhTVA3umU5hZc28V3kO4stgYryrTlLpuvgI9GiijltAjNbcqA==";
      };
    };
    "dunder-proto-1.0.1" = {
      name = "dunder-proto";
      packageName = "dunder-proto";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dunder-proto/-/dunder-proto-1.0.1.tgz";
        sha512 = "KIN/nDJBQRcXw0MLVhZE9iQHmG68qAVIBg9CqmUYjmQIhgij9U5MFvrqkUL5FbtyyzZuOeOt0zdeRe4UY7ct+A==";
      };
    };
    "ecdsa-sig-formatter-1.0.11" = {
      name = "ecdsa-sig-formatter";
      packageName = "ecdsa-sig-formatter";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecdsa-sig-formatter/-/ecdsa-sig-formatter-1.0.11.tgz";
        sha512 = "nagl3RYrbNv6kQkeJIpt6NJZy8twLB/2vtz6yN9Z4vRKHN4/QZJIEbqohALSgwKdnksuY3k5Addp5lg8sVoVcQ==";
      };
    };
    "effect-3.21.0" = {
      name = "effect";
      packageName = "effect";
      version = "3.21.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/effect/-/effect-3.21.0.tgz";
        sha512 = "PPN80qRokCd1f015IANNhrwOnLO7GrrMQfk4/lnZRE/8j7UPWrNNjPV0uBrZutI/nHzernbW+J0hdqQysHiSnQ==";
      };
    };
    "emmet-2.4.11" = {
      name = "emmet";
      packageName = "emmet";
      version = "2.4.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/emmet/-/emmet-2.4.11.tgz";
        sha512 = "23QPJB3moh/U9sT4rQzGgeyyGIrcM+GH5uVYg2C6wZIxAIJq7Ng3QLT79tl8FUwDXhyq9SusfknOrofAKqvgyQ==";
      };
    };
    "emoji-regex-10.6.0" = {
      name = "emoji-regex";
      packageName = "emoji-regex";
      version = "10.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-10.6.0.tgz";
        sha512 = "toUI84YS5YmxW219erniWD0CIVOo46xGKColeNQRgOzDorgBi1v4D71/OFzgD9GO2UGKIv1C3Sp8DAn0+j5w7A==";
      };
    };
    "entities-7.0.1" = {
      name = "entities";
      packageName = "entities";
      version = "7.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-7.0.1.tgz";
        sha512 = "TWrgLOFUQTH994YUyl1yT4uyavY5nNB5muff+RtWaqNVCAK408b5ZnnbNAUEWLTCpum9w6arT70i1XdQ4UeOPA==";
      };
    };
    "environment-1.1.0" = {
      name = "environment";
      packageName = "environment";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/environment/-/environment-1.1.0.tgz";
        sha512 = "xUtoPkMggbz0MPyPiIWr1Kp4aeWJjDZ6SMvURhimjdZgsRuDplF5/s9hcgGhyXMhs+6vpnuoiZ2kFiu3FMnS8Q==";
      };
    };
    "es-define-property-1.0.1" = {
      name = "es-define-property";
      packageName = "es-define-property";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-define-property/-/es-define-property-1.0.1.tgz";
        sha512 = "e3nRfgfUZ4rNGL232gUgX06QNyyez04KdjFrF+LTRoOXmrOgFKDg4BCdsjW8EnT69eqdYGmRpJwiPVYNrCaW3g==";
      };
    };
    "es-errors-1.3.0" = {
      name = "es-errors";
      packageName = "es-errors";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-errors/-/es-errors-1.3.0.tgz";
        sha512 = "Zf5H2Kxt2xjTvbJvP2ZWLEICxA6j+hAmMzIlypy4xcBg1vKVnx89Wy0GbS+kf5cwCVFFzdCFh2XSCFNULS6csw==";
      };
    };
    "es-object-atoms-1.1.1" = {
      name = "es-object-atoms";
      packageName = "es-object-atoms";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-object-atoms/-/es-object-atoms-1.1.1.tgz";
        sha512 = "FGgH2h8zKNim9ljj7dankFPcICIK9Cp5bm+c2gQSYePhpaG5+esrLODihIorn+Pe6FGJzWhXQotPv73jTaldXA==";
      };
    };
    "es-toolkit-1.45.1" = {
      name = "es-toolkit";
      packageName = "es-toolkit";
      version = "1.45.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-toolkit/-/es-toolkit-1.45.1.tgz";
        sha512 = "/jhoOj/Fx+A+IIyDNOvO3TItGmlMKhtX8ISAHKE90c4b/k1tqaqEZ+uUqfpU8DMnW5cgNJv606zS55jGvza0Xw==";
      };
    };
    "escape-string-regexp-2.0.0" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-2.0.0.tgz";
        sha512 = "UpzcLCXolUWcNu5HtVMHYdXJjArjsF9C0aNnquZYY4uW/Vu0miy5YoWvbV345HauVvcAUnpRuhMMcqTcGOY2+w==";
      };
    };
    "estree-walker-2.0.2" = {
      name = "estree-walker";
      packageName = "estree-walker";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/estree-walker/-/estree-walker-2.0.2.tgz";
        sha512 = "Rfkk/Mp/DL7JVje3u18FxFujQlTNR2q6QfMSMB7AvCBx91NGj/ba3kCfza0f6dVDbw7YlRf/nDrn7pQrCCyQ/w==";
      };
    };
    "execa-9.6.1" = {
      name = "execa";
      packageName = "execa";
      version = "9.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/execa/-/execa-9.6.1.tgz";
        sha512 = "9Be3ZoN4LmYR90tUoVu2te2BsbzHfhJyfEiAVfz7N5/zv+jduIfLrV2xdQXOHbaD6KgpGdO9PRPM1Y4Q9QkPkA==";
      };
    };
    "fast-check-3.23.2" = {
      name = "fast-check";
      packageName = "fast-check";
      version = "3.23.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-check/-/fast-check-3.23.2.tgz";
        sha512 = "h5+1OzzfCC3Ef7VbtKdcv7zsstUQwUDlYpUTvjeUsJAssPgLn7QzbboPtL5ro04Mq0rPOsMzl7q5hIbRs2wD1A==";
      };
    };
    "figures-6.1.0" = {
      name = "figures";
      packageName = "figures";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/figures/-/figures-6.1.0.tgz";
        sha512 = "d+l3qxjSesT4V7v2fh+QnmFnUWv9lSpjarhShNTgBOfA0ttejbQUAlHLitbjkoRiDulW0OPoQPYIGhIC8ohejg==";
      };
    };
    "function-bind-1.1.2" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.2.tgz";
        sha512 = "7XHNxH7qX9xG5mIwxkhumTox/MIRNcOgDrxWsMt2pAr23WHp6MrRlN7FBSFpCpr+oVO0F744iUgR82nJMfG2SA==";
      };
    };
    "generator-function-2.0.1" = {
      name = "generator-function";
      packageName = "generator-function";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/generator-function/-/generator-function-2.0.1.tgz";
        sha512 = "SFdFmIJi+ybC0vjlHN0ZGVGHc3lgE0DxPAT0djjVg+kjOnSqclqmj0KQ7ykTOLP6YxoqOvuAODGdcHJn+43q3g==";
      };
    };
    "get-east-asian-width-1.5.0" = {
      name = "get-east-asian-width";
      packageName = "get-east-asian-width";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-east-asian-width/-/get-east-asian-width-1.5.0.tgz";
        sha512 = "CQ+bEO+Tva/qlmw24dCejulK5pMzVnUOFOijVogd3KQs07HnRIgp8TGipvCCRT06xeYEbpbgwaCxglFyiuIcmA==";
      };
    };
    "get-intrinsic-1.3.1" = {
      name = "get-intrinsic";
      packageName = "get-intrinsic";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-intrinsic/-/get-intrinsic-1.3.1.tgz";
        sha512 = "fk1ZVEeOX9hVZ6QzoBNEC55+Ucqg4sTVwrVuigZhuRPESVFpMyXnd3sbXvPOwp7Y9riVyANiqhEuRF0G1aVSeQ==";
      };
    };
    "get-proto-1.0.1" = {
      name = "get-proto";
      packageName = "get-proto";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-proto/-/get-proto-1.0.1.tgz";
        sha512 = "sTSfBjoXBp89JvIKIefqw7U2CCebsc74kiY6awiGogKtoSGbgjYE/G/+l9sF3MWFPNc9IcoOC4ODfKHfxFmp0g==";
      };
    };
    "get-stream-9.0.1" = {
      name = "get-stream";
      packageName = "get-stream";
      version = "9.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stream/-/get-stream-9.0.1.tgz";
        sha512 = "kVCxPF3vQM/N0B1PmoqVUqgHP+EeVjmZSQn+1oCRPxd2P21P2F19lIgbR3HBosbB1PUhOAoctJnfEn2GbN2eZA==";
      };
    };
    "gopd-1.2.0" = {
      name = "gopd";
      packageName = "gopd";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/gopd/-/gopd-1.2.0.tgz";
        sha512 = "ZUKRh6/kUFoAiTAtTYPZJ3hw9wNxx+BIBOijnlG9PnrJsCcSjs1wyyD6vJpaYtgnzDrKYRSqf3OO6Rfa93xsRg==";
      };
    };
    "has-symbols-1.1.0" = {
      name = "has-symbols";
      packageName = "has-symbols";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-symbols/-/has-symbols-1.1.0.tgz";
        sha512 = "1cDNdwJ2Jaohmb3sg4OmKaMBwuC48sYni5HUw2DvsC8LjGTLK9h+eb1X6RyuOHe4hT0ULCW68iomhjUoKUqlPQ==";
      };
    };
    "has-tostringtag-1.0.2" = {
      name = "has-tostringtag";
      packageName = "has-tostringtag";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-tostringtag/-/has-tostringtag-1.0.2.tgz";
        sha512 = "NqADB8VjPFLM2V0VvHUewwwsw0ZWBaIdgo+ieHtK3hasLz4qeCRjYcqfB6AQrBggRKppKF8L52/VqdVsO47Dlw==";
      };
    };
    "hasown-2.0.2" = {
      name = "hasown";
      packageName = "hasown";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/hasown/-/hasown-2.0.2.tgz";
        sha512 = "0hJU9SCPvmMzIBdZFqNPXWa6dqh7WdH0cII9y+CyS8rG3nL48Bclra9HmKhVVUHyPWNH5Y7xDwAB7bfgSjkUMQ==";
      };
    };
    "hono-4.12.14" = {
      name = "hono";
      packageName = "hono";
      version = "4.12.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/hono/-/hono-4.12.14.tgz";
        sha512 = "am5zfg3yu6sqn5yjKBNqhnTX7Cv+m00ox+7jbaKkrLMRJ4rAdldd1xPd/JzbBWspqaQv6RSTrgFN95EsfhC+7w==";
      };
    };
    "http_ece-1.2.0" = {
      name = "http_ece";
      packageName = "http_ece";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http_ece/-/http_ece-1.2.0.tgz";
        sha512 = "JrF8SSLVmcvc5NducxgyOrKXe3EsyHMgBFgSaIUGmArKe+rwr0uphRkRXvwiom3I+fpIfoItveHrfudL8/rxuA==";
      };
    };
    "https-proxy-agent-7.0.6" = {
      name = "https-proxy-agent";
      packageName = "https-proxy-agent";
      version = "7.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/https-proxy-agent/-/https-proxy-agent-7.0.6.tgz";
        sha512 = "vK9P5/iUfdl95AI+JVyUuIcVtd4ofvtrOr3HNtM2yxC9bnMbEdp3x01OhQNnjb8IJYi38VlTE3mBXwcfvywuSw==";
      };
    };
    "human-signals-8.0.1" = {
      name = "human-signals";
      packageName = "human-signals";
      version = "8.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/human-signals/-/human-signals-8.0.1.tgz";
        sha512 = "eKCa6bwnJhvxj14kZk5NCPc6Hb6BdsU9DZcOnmQKSnO1VKrfV0zCvtttPZUsBvjmNDn8rpcJfpwSYnHBjc95MQ==";
      };
    };
    "indent-string-5.0.0" = {
      name = "indent-string";
      packageName = "indent-string";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/indent-string/-/indent-string-5.0.0.tgz";
        sha512 = "m6FAo/spmsW2Ab2fU35JTYwtOKa2yAwXSwgjSv1TJzh4Mh7mC3lzAOVLBprb72XsTrgkEIsl7YrFNAiDiRhIGg==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "ink-6.8.0" = {
      name = "ink";
      packageName = "ink";
      version = "6.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ink/-/ink-6.8.0.tgz";
        sha512 = "sbl1RdLOgkO9isK42WCZlJCFN9hb++sX9dsklOvfd1YQ3bQ2AiFu12Q6tFlr0HvEUvzraJntQCCpfEoUe9DSzA==";
      };
    };
    "ink-select-input-6.2.0" = {
      name = "ink-select-input";
      packageName = "ink-select-input";
      version = "6.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ink-select-input/-/ink-select-input-6.2.0.tgz";
        sha512 = "304fZXxkpYxJ9si5lxRCaX01GNlmPBgOZumXXRnPYbHW/iI31cgQynqk2tRypGLOF1cMIwPUzL2LSm6q4I5rQQ==";
      };
    };
    "ink-text-input-6.0.0" = {
      name = "ink-text-input";
      packageName = "ink-text-input";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ink-text-input/-/ink-text-input-6.0.0.tgz";
        sha512 = "Fw64n7Yha5deb1rHY137zHTAbSTNelUKuB5Kkk2HACXEtwIHBCf9OH2tP/LQ9fRYTl1F0dZgbW0zPnZk6FA9Lw==";
      };
    };
    "is-expression-4.0.0" = {
      name = "is-expression";
      packageName = "is-expression";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-expression/-/is-expression-4.0.0.tgz";
        sha512 = "zMIXX63sxzG3XrkHkrAPvm/OVZVSCPNkwMHU8oTX7/U3AL78I0QXCEICXUM13BIa8TYGZ68PiTKfQz3yaTNr4A==";
      };
    };
    "is-fullwidth-code-point-5.1.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-5.1.0.tgz";
        sha512 = "5XHYaSyiqADb4RnZ1Bdad6cPp8Toise4TzEjcOYDHZkTCbKgiUl7WTUCpNWHuxmDt91wnsZBc9xinNzopv3JMQ==";
      };
    };
    "is-in-ci-2.0.0" = {
      name = "is-in-ci";
      packageName = "is-in-ci";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-in-ci/-/is-in-ci-2.0.0.tgz";
        sha512 = "cFeerHriAnhrQSbpAxL37W1wcJKUUX07HyLWZCW1URJT/ra3GyUTzBgUnh24TMVfNTV2Hij2HLxkPHFZfOZy5w==";
      };
    };
    "is-plain-obj-4.1.0" = {
      name = "is-plain-obj";
      packageName = "is-plain-obj";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-plain-obj/-/is-plain-obj-4.1.0.tgz";
        sha512 = "+Pgi+vMuUNkJyExiMBt5IlFoMyKnr5zhJ4Uspz58WOhBF5QoIZkFyNHIbBAtHwzVAgk5RtndVNsDRN61/mmDqg==";
      };
    };
    "is-regex-1.2.1" = {
      name = "is-regex";
      packageName = "is-regex";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-regex/-/is-regex-1.2.1.tgz";
        sha512 = "MjYsKHO5O7mCsmRGxWcLWheFqN9DJ/2TmngvjKXihe6efViPqc274+Fx/4fYj/r03+ESvBdTXK0V6tA3rgez1g==";
      };
    };
    "is-stream-4.0.1" = {
      name = "is-stream";
      packageName = "is-stream";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-stream/-/is-stream-4.0.1.tgz";
        sha512 = "Dnz92NInDqYckGEUJv689RbRiTSEHCQ7wOVeALbkOz999YpqT46yMRIGtSNl2iCL1waAZSx40+h59NV/EwzV/A==";
      };
    };
    "is-unicode-supported-2.1.0" = {
      name = "is-unicode-supported";
      packageName = "is-unicode-supported";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-unicode-supported/-/is-unicode-supported-2.1.0.tgz";
        sha512 = "mE00Gnza5EEB3Ds0HfMyllZzbBrmLOX3vfWoj9A9PEnTfratQ/BcaJOuMhnkhjXvb2+FkY3VuHqtAGpTPmglFQ==";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha512 = "RHxMLp9lnKHGHRng9QFhRCMbYAcVpn69smSGcq3f36xjgVVWThj4qqLbTLlq7Ssj8B+fIQ1EuCEGI2lKsyQeIw==";
      };
    };
    "jsonc-parser-2.3.1" = {
      name = "jsonc-parser";
      packageName = "jsonc-parser";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonc-parser/-/jsonc-parser-2.3.1.tgz";
        sha512 = "H8jvkz1O50L3dMZCsLqiuB2tA7muqbSg1AtGEkN0leAqGjsUzDJir3Zwr02BhqdcITPg3ei3mZ+HjMocAknhhg==";
      };
    };
    "jsonc-parser-3.3.1" = {
      name = "jsonc-parser";
      packageName = "jsonc-parser";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonc-parser/-/jsonc-parser-3.3.1.tgz";
        sha512 = "HUgH65KyejrUFPvHFPbqOY0rsFip3Bo5wb4ngvdi1EpCYWUQDC5V+Y7mZws+DLkr4M//zQJoanu1SP+87Dv1oQ==";
      };
    };
    "jwa-2.0.1" = {
      name = "jwa";
      packageName = "jwa";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jwa/-/jwa-2.0.1.tgz";
        sha512 = "hRF04fqJIP8Abbkq5NKGN0Bbr3JxlQ+qhZufXVr0DvujKy93ZCbXZMHDL4EOtodSbCWxOqR8MS1tXA5hwqCXDg==";
      };
    };
    "jws-4.0.1" = {
      name = "jws";
      packageName = "jws";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jws/-/jws-4.0.1.tgz";
        sha512 = "EKI/M/yqPncGUUh44xz0PxSidXFr/+r0pA70+gIYhjv+et7yxM+s29Y+VGDkovRofQem0fs7Uvf4+YmAdyRduA==";
      };
    };
    "math-intrinsics-1.1.0" = {
      name = "math-intrinsics";
      packageName = "math-intrinsics";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/math-intrinsics/-/math-intrinsics-1.1.0.tgz";
        sha512 = "/IXtbwEk5HTPyEwyKX6hGkYXxM9nbj64B+ilVJnC/R6B0pH5G4V3b0pVbL7DBj4tkhBAppbQUlf6F6Xl9LHu1g==";
      };
    };
    "meow-14.1.0" = {
      name = "meow";
      packageName = "meow";
      version = "14.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/meow/-/meow-14.1.0.tgz";
        sha512 = "EDYo6VlmtnumlcBCbh1gLJ//9jvM/ndXHfVXIFrZVr6fGcwTUyCTFNTLCKuY3ffbK8L/+3Mzqnd58RojiZqHVw==";
      };
    };
    "mimic-fn-2.1.0" = {
      name = "mimic-fn";
      packageName = "mimic-fn";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-fn/-/mimic-fn-2.1.0.tgz";
        sha512 = "OqbOk5oEQeAZ8WXWydlu9HJjz9WVdEIvamMCcXmuqUYjTknH/sqsWvhQ3vgwKFRR1HpjvNBKQ37nbJgYzGqGcg==";
      };
    };
    "minimalistic-assert-1.0.1" = {
      name = "minimalistic-assert";
      packageName = "minimalistic-assert";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimalistic-assert/-/minimalistic-assert-1.0.1.tgz";
        sha512 = "UtJcAD4yEaGtjPezWuO9wC4nwUnVH/8/Im3yEHQP4b67cXlD/Qr9hdITCU1xDbSEXg2XKNaP8jsReV7vQd00/A==";
      };
    };
    "minimist-1.2.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.8.tgz";
        sha512 = "2yyAR8qBkN3YuheJanUpWC5U3bb5osDywNB8RzDVlDwDHbocAJveqqj1u8+SVD7jkWT4yvsHCpWqqWqAxb0zCA==";
      };
    };
    "ms-2.1.3" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.3.tgz";
        sha512 = "6FlzubTLZG3J2a/NVCAleEhjzq5oxgHyaCU9yYXvcLsvoVaHJq/s5xXI6/XXP6tz7R9xAOtHnSO/tXtF3WRTlA==";
      };
    };
    "muggle-string-0.4.1" = {
      name = "muggle-string";
      packageName = "muggle-string";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/muggle-string/-/muggle-string-0.4.1.tgz";
        sha512 = "VNTrAak/KhO2i8dqqnqnAHOa3cYBwXEZe9h+D5h/1ZqFSTEFHdM65lR7RoIqq3tBBYavsOXV84NoHXZ0AkPyqQ==";
      };
    };
    "npm-run-path-6.0.0" = {
      name = "npm-run-path";
      packageName = "npm-run-path";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-run-path/-/npm-run-path-6.0.0.tgz";
        sha512 = "9qny7Z9DsQU8Ou39ERsPU4OZQlSTP47ShQzuKZ6PRXpYLtIFgl/DEBYEXKlvcEa+9tHVcK8CF81Y2V72qaZhWA==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha512 = "rJgTQnkUnH1sFw8yT6VSU3zD3sWmu6sZhIseY8VX+GRu3P6F7Fu+JNDoXfklElbLJSnc3FUQHVe4cU5hj+BcUg==";
      };
    };
    "onetime-5.1.2" = {
      name = "onetime";
      packageName = "onetime";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/onetime/-/onetime-5.1.2.tgz";
        sha512 = "kbpaSSGJTWdAY5KPVeMOKXSrPtr8C8C7wodJbcsd51jRnmD+GZu8Y0VoU6Dm5Z4vWr0Ig/1NKuWRKf7j5aaYSg==";
      };
    };
    "parse-ms-4.0.0" = {
      name = "parse-ms";
      packageName = "parse-ms";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-ms/-/parse-ms-4.0.0.tgz";
        sha512 = "TXfryirbmq34y8QBwgqCVLi+8oA3oWx2eAnSn62ITyEhEYaWRlVZ2DvMM9eZbMs/RfxPu/PK/aBLyGj4IrqMHw==";
      };
    };
    "patch-console-2.0.0" = {
      name = "patch-console";
      packageName = "patch-console";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/patch-console/-/patch-console-2.0.0.tgz";
        sha512 = "0YNdUceMdaQwoKce1gatDScmMo5pu/tfABfnzEqeG0gtTmd7mh/WcwgUjtAeOU7N8nFFlbQBnFK2gXW5fGvmMA==";
      };
    };
    "path-browserify-1.0.1" = {
      name = "path-browserify";
      packageName = "path-browserify";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-browserify/-/path-browserify-1.0.1.tgz";
        sha512 = "b7uo2UCUOYZcnF/3ID0lulOJi/bafxa1xPe7ZPsammBSpjSWQkjNxlt635YGS2MiR9GjvuXCtz2emr3jbsz98g==";
      };
    };
    "path-key-3.1.1" = {
      name = "path-key";
      packageName = "path-key";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-key/-/path-key-3.1.1.tgz";
        sha512 = "ojmeN0qd+y0jszEtoY48r0Peq5dwMEkIlCOu6Q5f41lfkswXuKtYrhgoTpLnyIcHm24Uhqx+5Tqm2InSwLhE6Q==";
      };
    };
    "path-key-4.0.0" = {
      name = "path-key";
      packageName = "path-key";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-key/-/path-key-4.0.0.tgz";
        sha512 = "haREypq7xkM7ErfgIyA0z+Bj4AGKlMSdlQE2jvJo6huWD1EdkKYV+G/T4nq0YEF2vgTT8kqMFKo1uHn950r4SQ==";
      };
    };
    "picomatch-4.0.4" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "4.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-4.0.4.tgz";
        sha512 = "QP88BAKvMam/3NxH6vj2o21R6MjxZUAd6nlwAS/pnGvN9IVLocLHxGYIzFhg6fUQ+5th6P4dv4eW9jX3DSIj7A==";
      };
    };
    "pretty-ms-9.3.0" = {
      name = "pretty-ms";
      packageName = "pretty-ms";
      version = "9.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pretty-ms/-/pretty-ms-9.3.0.tgz";
        sha512 = "gjVS5hOP+M3wMm5nmNOucbIrqudzs9v/57bWRHQWLYklXqoXKrVfYW2W9+glfGsqtPgpiz5WwyEEB+ksXIx3gQ==";
      };
    };
    "pug-error-2.1.0" = {
      name = "pug-error";
      packageName = "pug-error";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-error/-/pug-error-2.1.0.tgz";
        sha512 = "lv7sU9e5Jk8IeUheHata6/UThZ7RK2jnaaNztxfPYUY+VxZyk/ePVaNZ/vwmH8WqGvDz3LrNYt/+gA55NDg6Pg==";
      };
    };
    "pug-lexer-5.0.1" = {
      name = "pug-lexer";
      packageName = "pug-lexer";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-lexer/-/pug-lexer-5.0.1.tgz";
        sha512 = "0I6C62+keXlZPZkOJeVam9aBLVP2EnbeDw3An+k0/QlqdwH6rv8284nko14Na7c0TtqtogfWXcRoFE4O4Ff20w==";
      };
    };
    "pug-parser-6.0.0" = {
      name = "pug-parser";
      packageName = "pug-parser";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-parser/-/pug-parser-6.0.0.tgz";
        sha512 = "ukiYM/9cH6Cml+AOl5kETtM9NR3WulyVP2y4HOU45DyMim1IeP/OOiyEWRr6qk5I5klpsBnbuHpwKmTx6WURnw==";
      };
    };
    "pure-rand-6.1.0" = {
      name = "pure-rand";
      packageName = "pure-rand";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pure-rand/-/pure-rand-6.1.0.tgz";
        sha512 = "bVWawvoZoBYpp6yIoQtQXHZjmz35RSVHnUOTefl8Vcjr8snTPY1wnpSPMWekcFwbxI6gtmT7rSYPFvz71ldiOA==";
      };
    };
    "qrcode-terminal-0.12.0" = {
      name = "qrcode-terminal";
      packageName = "qrcode-terminal";
      version = "0.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/qrcode-terminal/-/qrcode-terminal-0.12.0.tgz";
        sha512 = "EXtzRZmC+YGmGlDFbXKxQiMZNwCLEO6BANKXG4iCtSIM0yqc/pappSx3RIKr4r0uh5JsBckOXeKrB3Iz7mdQpQ==";
      };
    };
    "react-19.2.5" = {
      name = "react";
      packageName = "react";
      version = "19.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/react/-/react-19.2.5.tgz";
        sha512 = "llUJLzz1zTUBrskt2pwZgLq59AemifIftw4aB7JxOqf1HY2FDaGDxgwpAPVzHU1kdWabH7FauP4i1oEeer2WCA==";
      };
    };
    "react-devtools-core-6.1.5" = {
      name = "react-devtools-core";
      packageName = "react-devtools-core";
      version = "6.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-devtools-core/-/react-devtools-core-6.1.5.tgz";
        sha512 = "ePrwPfxAnB+7hgnEr8vpKxL9cmnp7F322t8oqcPshbIQQhDKgFDW4tjhF2wjVbdXF9O/nyuy3sQWd9JGpiLPvA==";
      };
    };
    "react-dom-19.2.5" = {
      name = "react-dom";
      packageName = "react-dom";
      version = "19.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-dom/-/react-dom-19.2.5.tgz";
        sha512 = "J5bAZz+DXMMwW/wV3xzKke59Af6CHY7G4uYLN1OvBcKEsWOs4pQExj86BBKamxl/Ik5bx9whOrvBlSDfWzgSag==";
      };
    };
    "react-reconciler-0.33.0" = {
      name = "react-reconciler";
      packageName = "react-reconciler";
      version = "0.33.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-reconciler/-/react-reconciler-0.33.0.tgz";
        sha512 = "KetWRytFv1epdpJc3J4G75I4WrplZE5jOL7Yq0p34+OVOKF4Se7WrdIdVC45XsSSmUTlht2FM/fM1FZb1mfQeA==";
      };
    };
    "request-light-0.7.0" = {
      name = "request-light";
      packageName = "request-light";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/request-light/-/request-light-0.7.0.tgz";
        sha512 = "lMbBMrDoxgsyO+yB3sDcrDuX85yYt7sS8BfQd11jtbW/z5ZWgLZRcEGLsLoYw7I0WSUGQBs8CC8ScIxkTX1+6Q==";
      };
    };
    "restore-cursor-4.0.0" = {
      name = "restore-cursor";
      packageName = "restore-cursor";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/restore-cursor/-/restore-cursor-4.0.0.tgz";
        sha512 = "I9fPXU9geO9bHOt9pHHOhOkYerIMsmVaWB0rA2AI9ERh/+x/i7MV5HKBNrg+ljO5eoPVgCcnFuRjJ9uH6I/3eg==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "scheduler-0.27.0" = {
      name = "scheduler";
      packageName = "scheduler";
      version = "0.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/scheduler/-/scheduler-0.27.0.tgz";
        sha512 = "eNv+WrVbKu1f3vbYJT/xtiF5syA5HPIMtf9IgY/nKg0sWqzAUEvqY/xm7OcZc/qafLx/iO9FgOmeSAp4v5ti/Q==";
      };
    };
    "semver-7.7.4" = {
      name = "semver";
      packageName = "semver";
      version = "7.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.7.4.tgz";
        sha512 = "vFKC2IEtQnVhpT78h1Yp8wzwrf8CM+MzKMHGJZfBtzhZNycRFnXsHk6E5TxIkkMsgNS7mdX3AGB7x2QM2di4lA==";
      };
    };
    "shebang-command-2.0.0" = {
      name = "shebang-command";
      packageName = "shebang-command";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-command/-/shebang-command-2.0.0.tgz";
        sha512 = "kHxr2zZpYtdmrN1qDjrrX/Z1rR1kG8Dx+gkpK1G4eXmvXswmcE1hTWBWYUzlraYw1/yZp6YuDY77YtvbN0dmDA==";
      };
    };
    "shebang-regex-3.0.0" = {
      name = "shebang-regex";
      packageName = "shebang-regex";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-regex/-/shebang-regex-3.0.0.tgz";
        sha512 = "7++dFhtcx3353uBaq8DDR4NuxBetBzC7ZQOhmTQInHEd6bSrXdiEyzCvG07Z44UYdLShWUyXt5M/yhz8ekcb1A==";
      };
    };
    "shell-quote-1.8.3" = {
      name = "shell-quote";
      packageName = "shell-quote";
      version = "1.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/shell-quote/-/shell-quote-1.8.3.tgz";
        sha512 = "ObmnIF4hXNg1BqhnHmgbDETF8dLPCggZWBjkQfhZpbszZnYur5DUljTcCHii5LC3J5E0yeO/1LIMyH+UvHQgyw==";
      };
    };
    "signal-exit-3.0.7" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.7.tgz";
        sha512 = "wnD2ZE+l+SPC/uoS0vXeE9L1+0wuaMqKlfz9AMUo38JsyLSBWSFcHR1Rri62LZc12vLr1gb3jl7iwQhgwpAbGQ==";
      };
    };
    "signal-exit-4.1.0" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-4.1.0.tgz";
        sha512 = "bzyZ1e88w9O1iNJbKnOlvYTrWPDl46O1bG0D3XInv+9tkPrxrN8jUUTiFlDkkmKWgn1M6CfIA13SuGqOa9Korw==";
      };
    };
    "slice-ansi-8.0.0" = {
      name = "slice-ansi";
      packageName = "slice-ansi";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/slice-ansi/-/slice-ansi-8.0.0.tgz";
        sha512 = "stxByr12oeeOyY2BlviTNQlYV5xOj47GirPr4yA1hE9JCtxfQN0+tVbkxwCtYDQWhEKWFHsEK48ORg5jrouCAg==";
      };
    };
    "source-map-js-1.2.1" = {
      name = "source-map-js";
      packageName = "source-map-js";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-js/-/source-map-js-1.2.1.tgz";
        sha512 = "UXWMKhLOwVKb728IUtQPXxfYU+usdybtUrK/8uGE8CQMvrhOpwvzDBwj0QhSL7MQc7vIsISBG8VQ8+IDQxpfQA==";
      };
    };
    "stack-utils-2.0.6" = {
      name = "stack-utils";
      packageName = "stack-utils";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/stack-utils/-/stack-utils-2.0.6.tgz";
        sha512 = "XlkWvfIm6RmsWtNJx+uqtKLS8eqFbxUg0ZzLXqY0caEy9l7hruX8IpiDnjsLavoBgqCCR71TqWO8MaXYheJ3RQ==";
      };
    };
    "string-width-7.2.0" = {
      name = "string-width";
      packageName = "string-width";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-7.2.0.tgz";
        sha512 = "tsaTIkKW9b4N+AEj+SVA+WhJzV7/zMhcSu78mLKWSk7cXMOSHsBKFWUs0fWwq8QyK3MgJBQRX6Gbi4kYbdvGkQ==";
      };
    };
    "string-width-8.2.0" = {
      name = "string-width";
      packageName = "string-width";
      version = "8.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-8.2.0.tgz";
        sha512 = "6hJPQ8N0V0P3SNmP6h2J99RLuzrWz2gvT7VnK5tKvrNqJoyS9W4/Fb8mo31UiPvy00z7DQXkP2hnKBVav76thw==";
      };
    };
    "strip-ansi-7.2.0" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-7.2.0.tgz";
        sha512 = "yDPMNjp4WyfYBkHnjIRLfca1i6KMyGCtsVgoKe/z1+6vukgaENdgGBZt+ZmKPc4gavvEZ5OgHfHdrazhgNyG7w==";
      };
    };
    "strip-final-newline-4.0.0" = {
      name = "strip-final-newline";
      packageName = "strip-final-newline";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-final-newline/-/strip-final-newline-4.0.0.tgz";
        sha512 = "aulFJcD6YK8V1G7iRB5tigAP4TsHBZZrOV8pjV++zdUwmeV8uzbY7yn6h9MswN62adStNZFuCIx4haBnRuMDaw==";
      };
    };
    "tagged-tag-1.0.0" = {
      name = "tagged-tag";
      packageName = "tagged-tag";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tagged-tag/-/tagged-tag-1.0.0.tgz";
        sha512 = "yEFYrVhod+hdNyx7g5Bnkkb0G6si8HJurOoOEgC8B/O0uXLHlaey/65KRv6cuWBNhBgHKAROVpc7QyYqE5gFng==";
      };
    };
    "terminal-size-4.0.1" = {
      name = "terminal-size";
      packageName = "terminal-size";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/terminal-size/-/terminal-size-4.0.1.tgz";
        sha512 = "avMLDQpUI9I5XFrklECw1ZEUPJhqzcwSWsyyI8blhRLT+8N1jLJWLWWYQpB2q2xthq8xDvjZPISVh53T/+CLYQ==";
      };
    };
    "to-rotated-1.0.0" = {
      name = "to-rotated";
      packageName = "to-rotated";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-rotated/-/to-rotated-1.0.0.tgz";
        sha512 = "KsEID8AfgUy+pxVRLsWp0VzCa69wxzUDZnzGbyIST/bcgcrMvTYoFBX/QORH4YApoD89EDuUovx4BTdpOn319Q==";
      };
    };
    "token-stream-1.0.0" = {
      name = "token-stream";
      packageName = "token-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/token-stream/-/token-stream-1.0.0.tgz";
        sha512 = "VSsyNPPW74RpHwR8Fc21uubwHY7wMDeJLys2IX5zJNih+OnAnaifKHo+1LHT7DAdloQ7apeaaWg8l7qnf/TnEg==";
      };
    };
    "type-fest-4.41.0" = {
      name = "type-fest";
      packageName = "type-fest";
      version = "4.41.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-fest/-/type-fest-4.41.0.tgz";
        sha512 = "TeTSQ6H5YHvpqVwBRcnLDCBnDOHWYu7IvGbHT6N8AOymcr9PJGjc1GTtiWZTYg0NCgYwvnYWEkVChQAr9bjfwA==";
      };
    };
    "type-fest-5.5.0" = {
      name = "type-fest";
      packageName = "type-fest";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-fest/-/type-fest-5.5.0.tgz";
        sha512 = "PlBfpQwiUvGViBNX84Yxwjsdhd1TUlXr6zjX7eoirtCPIr08NAmxwa+fcYBTeRQxHo9YC9wwF3m9i700sHma8g==";
      };
    };
    "typescript-auto-import-cache-0.3.6" = {
      name = "typescript-auto-import-cache";
      packageName = "typescript-auto-import-cache";
      version = "0.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript-auto-import-cache/-/typescript-auto-import-cache-0.3.6.tgz";
        sha512 = "RpuHXrknHdVdK7wv/8ug3Fr0WNsNi5l5aB8MYYuXhq2UH5lnEB1htJ1smhtD5VeCsGr2p8mUDtd83LCQDFVgjQ==";
      };
    };
    "unicorn-magic-0.3.0" = {
      name = "unicorn-magic";
      packageName = "unicorn-magic";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unicorn-magic/-/unicorn-magic-0.3.0.tgz";
        sha512 = "+QBBXBCvifc56fsbuxZQ6Sic3wqqc3WWaqxs58gvJrcOuN83HGTCwz3oS5phzU9LthRNE9VrJCFCLUgHeeFnfA==";
      };
    };
    "volar-service-css-0.0.70" = {
      name = "volar-service-css";
      packageName = "volar-service-css";
      version = "0.0.70";
      src = fetchurl {
        url = "https://registry.npmjs.org/volar-service-css/-/volar-service-css-0.0.70.tgz";
        sha512 = "K1qyOvBpE3rzdAv3e4/6Rv5yizrYPy5R/ne3IWCAzLBuMO4qBMV3kSqWzj6KUVe6S0AnN6wxF7cRkiaKfYMYJw==";
      };
    };
    "volar-service-emmet-0.0.70" = {
      name = "volar-service-emmet";
      packageName = "volar-service-emmet";
      version = "0.0.70";
      src = fetchurl {
        url = "https://registry.npmjs.org/volar-service-emmet/-/volar-service-emmet-0.0.70.tgz";
        sha512 = "xi5bC4m/VyE3zy/n2CXspKeDZs3qA41tHLTw275/7dNWM/RqE2z3BnDICQybHIVp/6G1iOQj5c1qXMgQC08TNg==";
      };
    };
    "volar-service-html-0.0.70" = {
      name = "volar-service-html";
      packageName = "volar-service-html";
      version = "0.0.70";
      src = fetchurl {
        url = "https://registry.npmjs.org/volar-service-html/-/volar-service-html-0.0.70.tgz";
        sha512 = "eR6vCgMdmYAo4n+gcT7DSyBQbwB8S3HZZvSagTf0sxNaD4WppMCFfpqWnkrlGStPKMZvMiejRRVmqsX9dYcTvQ==";
      };
    };
    "volar-service-json-0.0.70" = {
      name = "volar-service-json";
      packageName = "volar-service-json";
      version = "0.0.70";
      src = fetchurl {
        url = "https://registry.npmjs.org/volar-service-json/-/volar-service-json-0.0.70.tgz";
        sha512 = "cRP18LqxZU3vYsSqm2wQ5de689SlTnQ7iuHj/9SeVvfUncu8S0pmobMPnSZCzqkQzt2tbAvz4UNugVOyqhkQLw==";
      };
    };
    "volar-service-pug-0.0.70" = {
      name = "volar-service-pug";
      packageName = "volar-service-pug";
      version = "0.0.70";
      src = fetchurl {
        url = "https://registry.npmjs.org/volar-service-pug/-/volar-service-pug-0.0.70.tgz";
        sha512 = "9P+hgNVfd0BpdwBcErBNLESH4K66BEOZIPwjAb3DBpbTkPfQXa2r6MAvz/nkIh/bOG7/OO3W1eEPJRUEqzUOmw==";
      };
    };
    "volar-service-pug-beautify-0.0.70" = {
      name = "volar-service-pug-beautify";
      packageName = "volar-service-pug-beautify";
      version = "0.0.70";
      src = fetchurl {
        url = "https://registry.npmjs.org/volar-service-pug-beautify/-/volar-service-pug-beautify-0.0.70.tgz";
        sha512 = "4Ji7d4srisSSaFs6AfcobtzjAJUVobs3UfyWVhxuJnjcL5DsqbwFv2iwGCvGGTJmZxm1PbPN9r5tkUnPr8ZAOA==";
      };
    };
    "volar-service-typescript-0.0.70" = {
      name = "volar-service-typescript";
      packageName = "volar-service-typescript";
      version = "0.0.70";
      src = fetchurl {
        url = "https://registry.npmjs.org/volar-service-typescript/-/volar-service-typescript-0.0.70.tgz";
        sha512 = "l46Bx4cokkUedTd74ojO5H/zqHZJ8SUuyZ0IB8JN4jfRqUM3bQFBHoOwlZCyZmOeO0A3RQNkMnFclxO4c++gsg==";
      };
    };
    "vscode-css-languageservice-6.3.10" = {
      name = "vscode-css-languageservice";
      packageName = "vscode-css-languageservice";
      version = "6.3.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-css-languageservice/-/vscode-css-languageservice-6.3.10.tgz";
        sha512 = "eq5N9Er3fC4vA9zd9EFhyBG90wtCCuXgRSpAndaOgXMh1Wgep5lBgRIeDgjZBW9pa+332yC9+49cZMW8jcL3MA==";
      };
    };
    "vscode-html-languageservice-5.6.2" = {
      name = "vscode-html-languageservice";
      packageName = "vscode-html-languageservice";
      version = "5.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-html-languageservice/-/vscode-html-languageservice-5.6.2.tgz";
        sha512 = "ulCrSnFnfQ16YzvwnYUgEbUEl/ZG7u2eV27YhvLObSHKkb8fw1Z9cgsnUwjTEeDIdJDoTDTDpxuhQwoenoLNMg==";
      };
    };
    "vscode-json-languageservice-5.7.2" = {
      name = "vscode-json-languageservice";
      packageName = "vscode-json-languageservice";
      version = "5.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-json-languageservice/-/vscode-json-languageservice-5.7.2.tgz";
        sha512 = "WtKRDtJfFEmLrgtu+ODexOHm/6/krRF0k6t+uvkKIKW1Jh9ZIyxZQwJJwB3qhrEgvAxa37zbUg+vn+UyUK/U2w==";
      };
    };
    "vscode-jsonrpc-8.2.0" = {
      name = "vscode-jsonrpc";
      packageName = "vscode-jsonrpc";
      version = "8.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-8.2.0.tgz";
        sha512 = "C+r0eKJUIfiDIfwJhria30+TYWPtuHJXHtI7J0YlOmKAo7ogxP20T0zxB7HZQIFhIyvoBPwWskjxrvAtfjyZfA==";
      };
    };
    "vscode-languageserver-9.0.1" = {
      name = "vscode-languageserver";
      packageName = "vscode-languageserver";
      version = "9.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver/-/vscode-languageserver-9.0.1.tgz";
        sha512 = "woByF3PDpkHFUreUa7Hos7+pUWdeWMXRd26+ZX2A8cFx6v/JPTtd4/uN0/jB6XQHYaOlHbio03NTHCqrgG5n7g==";
      };
    };
    "vscode-languageserver-protocol-3.17.5" = {
      name = "vscode-languageserver-protocol";
      packageName = "vscode-languageserver-protocol";
      version = "3.17.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-protocol/-/vscode-languageserver-protocol-3.17.5.tgz";
        sha512 = "mb1bvRJN8SVznADSGWM9u/b07H7Ecg0I3OgXDuLdn307rl/J3A9YD6/eYOssqhecL27hK1IPZAsaqh00i/Jljg==";
      };
    };
    "vscode-languageserver-textdocument-1.0.12" = {
      name = "vscode-languageserver-textdocument";
      packageName = "vscode-languageserver-textdocument";
      version = "1.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-textdocument/-/vscode-languageserver-textdocument-1.0.12.tgz";
        sha512 = "cxWNPesCnQCcMPeenjKKsOCKQZ/L6Tv19DTRIGuLWe32lyzWhihGVJ/rcckZXJxfdKCFvRLS3fpBIsV/ZGX4zA==";
      };
    };
    "vscode-languageserver-types-3.17.5" = {
      name = "vscode-languageserver-types";
      packageName = "vscode-languageserver-types";
      version = "3.17.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.17.5.tgz";
        sha512 = "Ld1VelNuX9pdF39h2Hgaeb5hEZM2Z3jUrrMgWQAu82jMtZp7p3vJT3BzToKtZI7NgQssZje5o0zryOrhQvzQAg==";
      };
    };
    "vscode-nls-5.2.0" = {
      name = "vscode-nls";
      packageName = "vscode-nls";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-nls/-/vscode-nls-5.2.0.tgz";
        sha512 = "RAaHx7B14ZU04EU31pT+rKz2/zSl7xMsfIZuo8pd+KZO6PXtQmpevpq3vxvWNcrGbdmhM/rr5Uw5Mz+NBfhVng==";
      };
    };
    "vscode-uri-3.1.0" = {
      name = "vscode-uri";
      packageName = "vscode-uri";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-uri/-/vscode-uri-3.1.0.tgz";
        sha512 = "/BpdSx+yCQGnCvecbyXdxHDkuk55/G3xwnC0GqY4gmQ3j+A+g8kzzgB4Nk/SINjqn6+waqw3EgbVF2QKExkRxQ==";
      };
    };
    "vue-component-meta-3.2.6" = {
      name = "vue-component-meta";
      packageName = "vue-component-meta";
      version = "3.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/vue-component-meta/-/vue-component-meta-3.2.6.tgz";
        sha512 = "Tlo84lGrHrsE5nJ2lAQDiN+hP9nagKxR3E7kXEidAyYrQzBixaDD/6jwLgDYlmIoyjGCn3BLEC7gGNGObU2Y7w==";
      };
    };
    "web-push-3.6.7" = {
      name = "web-push";
      packageName = "web-push";
      version = "3.6.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/web-push/-/web-push-3.6.7.tgz";
        sha512 = "OpiIUe8cuGjrj3mMBFWY+e4MMIkW3SVT+7vEIjvD9kejGUypv8GPDf84JdPWskK8zMRIJ6xYGm+Kxr8YkPyA0A==";
      };
    };
    "which-2.0.2" = {
      name = "which";
      packageName = "which";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-2.0.2.tgz";
        sha512 = "BLI3Tl1TW3Pvl70l3yq3Y64i+awpwXqsGBYWkkqMtnbXgrMD+yj7rhW0kuEDxzJaYXGjEW5ogapKNMEKNMjibA==";
      };
    };
    "widest-line-6.0.0" = {
      name = "widest-line";
      packageName = "widest-line";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/widest-line/-/widest-line-6.0.0.tgz";
        sha512 = "U89AsyEeAsyoF0zVJBkG9zBgekjgjK7yk9sje3F4IQpXBJ10TF6ByLlIfjMhcmHMJgHZI4KHt4rdNfktzxIAMA==";
      };
    };
    "wrap-ansi-9.0.2" = {
      name = "wrap-ansi";
      packageName = "wrap-ansi";
      version = "9.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-9.0.2.tgz";
        sha512 = "42AtmgqjV+X1VpdOfyTGOYRi0/zsoLqtXQckTmqTeybT+BDIbM/Guxo7x3pE2vtpr1ok6xRqM9OpBe+Jyoqyww==";
      };
    };
    "ws-7.5.10" = {
      name = "ws";
      packageName = "ws";
      version = "7.5.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-7.5.10.tgz";
        sha512 = "+dbF1tHwZpXcbOJdVOkzLDxZP1ailvSxM6ZweXTegylPny803bFhA+vqBYw4s31NSAk4S2Qz+AKXK9a4wkdjcQ==";
      };
    };
    "ws-8.20.0" = {
      name = "ws";
      packageName = "ws";
      version = "8.20.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-8.20.0.tgz";
        sha512 = "sAt8BhgNbzCtgGbt2OxmpuryO63ZoDk/sqaB/znQm94T4fCEsy/yV+7CdC1kJhOU9lboAEU7R3kquuycDoibVA==";
      };
    };
    "yaml-2.8.3" = {
      name = "yaml";
      packageName = "yaml";
      version = "2.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/yaml/-/yaml-2.8.3.tgz";
        sha512 = "AvbaCLOO2Otw/lW5bmh9d/WEdcDFdQp2Z2ZUH3pX9U2ihyUY0nvLv7J6TrWowklRGPYbB/IuIMfYgxaCPg5Bpg==";
      };
    };
    "yoctocolors-2.1.2" = {
      name = "yoctocolors";
      packageName = "yoctocolors";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/yoctocolors/-/yoctocolors-2.1.2.tgz";
        sha512 = "CzhO+pFNo8ajLM2d2IW/R93ipy99LWjtwblvC1RsoSUMZgyLbYFr221TnSNT7GjGdYui6P459mw9JH/g/zW2ug==";
      };
    };
    "yoga-layout-3.2.1" = {
      name = "yoga-layout";
      packageName = "yoga-layout";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yoga-layout/-/yoga-layout-3.2.1.tgz";
        sha512 = "0LPOt3AxKqMdFBZA3HBAt/t/8vIKq7VaQYbuA8WxCgung+p9TVyKRYdpvCb80HcdTN2NkbIKbhNwKUfm3tQywQ==";
      };
    };
    "zod-4.3.6" = {
      name = "zod";
      packageName = "zod";
      version = "4.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/zod/-/zod-4.3.6.tgz";
        sha512 = "rftlrkhHZOcjDwkGlnUtZZkvaPHCsDATp4pGpuOOMDaTdDDXF91wuVDJoWoPsKX/3YPQ5fHuF3STjcYyKr+Qhg==";
      };
    };
  };
in
{
  "@anthropic-ai/claude-code" = nodeEnv.buildNodePackage {
    name = "_at_anthropic-ai_slash_claude-code";
    packageName = "@anthropic-ai/claude-code";
    version = "2.1.112";
    src = fetchurl {
      url = "https://registry.npmjs.org/@anthropic-ai/claude-code/-/claude-code-2.1.112.tgz";
      sha512 = "9FUgJ0EOvILyhIqxFKNVliebiUjL68dwpEW3eGSSe0vkVDJ1c5qMDNWc22gW3zkD7zRAqtfQPSGv0t4vMM2DPA==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Use Claude, Anthropic's AI assistant, right from your terminal. Claude can understand your codebase, edit files, run terminal commands, and handle entire workflows for you.";
      homepage = "https://github.com/anthropics/claude-code";
      license = "SEE LICENSE IN README.md";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "@vue/language-server" = nodeEnv.buildNodePackage {
    name = "_at_vue_slash_language-server";
    packageName = "@vue/language-server";
    version = "3.2.6";
    src = fetchurl {
      url = "https://registry.npmjs.org/@vue/language-server/-/language-server-3.2.6.tgz";
      sha512 = "quU6+4aa7xEOorwYNoS7FT85K6jVfMiCHew2YtKtVWUxI/UjRePpvewrhXYykiwUZ498U5Lf5V4vJSQsAxI/5w==";
    };
    dependencies = [
      sources."@babel/helper-string-parser-7.27.1"
      sources."@babel/helper-validator-identifier-7.28.5"
      sources."@babel/parser-7.29.2"
      sources."@babel/types-7.29.0"
      sources."@emmetio/abbreviation-2.3.3"
      sources."@emmetio/css-abbreviation-2.1.8"
      sources."@emmetio/css-parser-0.4.1"
      sources."@emmetio/html-matcher-1.3.0"
      sources."@emmetio/scanner-1.0.4"
      sources."@emmetio/stream-reader-2.2.0"
      sources."@emmetio/stream-reader-utils-0.1.0"
      sources."@johnsoncodehk/pug-beautify-0.2.2"
      sources."@volar/language-core-2.4.28"
      sources."@volar/language-server-2.4.28"
      sources."@volar/language-service-2.4.28"
      sources."@volar/source-map-2.4.28"
      sources."@volar/typescript-2.4.28"
      sources."@vscode/emmet-helper-2.11.0"
      sources."@vscode/l10n-0.0.18"
      sources."@vue/compiler-core-3.5.32"
      sources."@vue/compiler-dom-3.5.32"
      sources."@vue/language-core-3.2.6"
      sources."@vue/language-plugin-pug-3.2.6"
      sources."@vue/language-service-3.2.6"
      sources."@vue/shared-3.5.32"
      sources."@vue/typescript-plugin-3.2.6"
      sources."acorn-7.4.1"
      sources."alien-signals-3.1.2"
      sources."async-function-1.0.0"
      sources."async-generator-function-1.0.0"
      sources."call-bind-apply-helpers-1.0.2"
      sources."call-bound-1.0.4"
      sources."character-parser-2.2.0"
      sources."dunder-proto-1.0.1"
      sources."emmet-2.4.11"
      sources."entities-7.0.1"
      sources."es-define-property-1.0.1"
      sources."es-errors-1.3.0"
      sources."es-object-atoms-1.1.1"
      sources."estree-walker-2.0.2"
      sources."function-bind-1.1.2"
      sources."generator-function-2.0.1"
      sources."get-intrinsic-1.3.1"
      sources."get-proto-1.0.1"
      sources."gopd-1.2.0"
      sources."has-symbols-1.1.0"
      sources."has-tostringtag-1.0.2"
      sources."hasown-2.0.2"
      sources."is-expression-4.0.0"
      sources."is-regex-1.2.1"
      sources."jsonc-parser-2.3.1"
      sources."math-intrinsics-1.1.0"
      sources."muggle-string-0.4.1"
      sources."object-assign-4.1.1"
      sources."path-browserify-1.0.1"
      sources."picomatch-4.0.4"
      sources."pug-error-2.1.0"
      sources."pug-lexer-5.0.1"
      sources."pug-parser-6.0.0"
      sources."request-light-0.7.0"
      sources."semver-7.7.4"
      sources."source-map-js-1.2.1"
      sources."token-stream-1.0.0"
      sources."typescript-auto-import-cache-0.3.6"
      sources."volar-service-css-0.0.70"
      sources."volar-service-emmet-0.0.70"
      sources."volar-service-html-0.0.70"
      sources."volar-service-json-0.0.70"
      sources."volar-service-pug-0.0.70"
      sources."volar-service-pug-beautify-0.0.70"
      sources."volar-service-typescript-0.0.70"
      sources."vscode-css-languageservice-6.3.10"
      sources."vscode-html-languageservice-5.6.2"
      (sources."vscode-json-languageservice-5.7.2" // {
        dependencies = [
          sources."jsonc-parser-3.3.1"
        ];
      })
      sources."vscode-jsonrpc-8.2.0"
      sources."vscode-languageserver-9.0.1"
      sources."vscode-languageserver-protocol-3.17.5"
      sources."vscode-languageserver-textdocument-1.0.12"
      sources."vscode-languageserver-types-3.17.5"
      sources."vscode-nls-5.2.0"
      sources."vscode-uri-3.1.0"
      sources."vue-component-meta-3.2.6"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "<p>   <a href=\"https://www.npmjs.com/package/@vue/language-server\"><img src=\"https://img.shields.io/npm/v/@vue/language-server.svg?labelColor=18181B&color=1584FC\" alt=\"NPM version\"></a>   <a href=\"https://github.com/vuejs/language-tools/blob/master/LICENS";
      homepage = "https://github.com/vuejs/language-tools#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "@vue/typescript-plugin" = nodeEnv.buildNodePackage {
    name = "_at_vue_slash_typescript-plugin";
    packageName = "@vue/typescript-plugin";
    version = "3.2.6";
    src = fetchurl {
      url = "https://registry.npmjs.org/@vue/typescript-plugin/-/typescript-plugin-3.2.6.tgz";
      sha512 = "D7DO3/MDrdRAxZSpZU8SFBgk4a3d1yk75eKbDqAg7eM/AgpL7ur+PEuwqnOQiwFGEdtrhuFhiqksUtnzJHiq+w==";
    };
    dependencies = [
      sources."@babel/helper-string-parser-7.27.1"
      sources."@babel/helper-validator-identifier-7.28.5"
      sources."@babel/parser-7.29.2"
      sources."@babel/types-7.29.0"
      sources."@volar/language-core-2.4.28"
      sources."@volar/source-map-2.4.28"
      sources."@volar/typescript-2.4.28"
      sources."@vue/compiler-core-3.5.32"
      sources."@vue/compiler-dom-3.5.32"
      sources."@vue/language-core-3.2.6"
      sources."@vue/shared-3.5.32"
      sources."alien-signals-3.1.2"
      sources."entities-7.0.1"
      sources."estree-walker-2.0.2"
      sources."muggle-string-0.4.1"
      sources."path-browserify-1.0.1"
      sources."picomatch-4.0.4"
      sources."source-map-js-1.2.1"
      sources."vscode-uri-3.1.0"
      sources."vue-component-meta-3.2.6"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "<p>   <a href=\"https://www.npmjs.com/package/@vue/typescript-plugin\"><img src=\"https://img.shields.io/npm/v/@vue/typescript-plugin.svg?labelColor=18181B&color=1584FC\" alt=\"NPM version\"></a>   <a href=\"https://github.com/vuejs/language-tools/blob/master/LI";
      homepage = "https://github.com/vuejs/language-tools#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  agent-browser = nodeEnv.buildNodePackage {
    name = "agent-browser";
    packageName = "agent-browser";
    version = "0.26.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/agent-browser/-/agent-browser-0.26.0.tgz";
      sha512 = "pdqSfjwbFSp+qnwlb2g23e9wXveIOfMi19xpPA9xZUbzEAUp6W4YBZj6Ybj8z4M7WkcbGDDYc+oDIHDt9R3EDQ==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Browser automation CLI for AI agents";
      homepage = "https://agent-browser.dev";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  ccmanager = nodeEnv.buildNodePackage {
    name = "ccmanager";
    packageName = "ccmanager";
    version = "4.1.7";
    src = fetchurl {
      url = "https://registry.npmjs.org/ccmanager/-/ccmanager-4.1.7.tgz";
      sha512 = "1D+GFd/LbMkBahLlaXyQhMx3b3XdSWGCnbBaSBZf2cyYiVN9unNpyYIE8KIrlPlDR5HH8Wxr0tIgkiSS1CnE9Q==";
    };
    dependencies = [
      sources."@alcalzone/ansi-tokenize-0.2.5"
      sources."@standard-schema/spec-1.1.0"
      sources."@xterm/addon-serialize-0.14.0"
      sources."@xterm/headless-6.0.0"
      sources."ansi-escapes-7.3.0"
      sources."ansi-regex-6.2.2"
      sources."ansi-styles-6.2.3"
      sources."auto-bind-5.0.1"
      sources."chalk-5.6.2"
      sources."cli-boxes-3.0.0"
      sources."cli-cursor-4.0.0"
      sources."cli-truncate-5.2.0"
      sources."code-excerpt-4.0.0"
      sources."convert-to-spaces-2.0.1"
      sources."effect-3.21.0"
      sources."emoji-regex-10.6.0"
      sources."environment-1.1.0"
      sources."es-toolkit-1.45.1"
      sources."escape-string-regexp-2.0.0"
      sources."fast-check-3.23.2"
      sources."figures-6.1.0"
      sources."get-east-asian-width-1.5.0"
      sources."indent-string-5.0.0"
      sources."ink-6.8.0"
      sources."ink-select-input-6.2.0"
      (sources."ink-text-input-6.0.0" // {
        dependencies = [
          sources."type-fest-4.41.0"
        ];
      })
      sources."is-fullwidth-code-point-5.1.0"
      sources."is-in-ci-2.0.0"
      sources."is-unicode-supported-2.1.0"
      sources."meow-14.1.0"
      sources."mimic-fn-2.1.0"
      sources."onetime-5.1.2"
      sources."patch-console-2.0.0"
      sources."pure-rand-6.1.0"
      sources."react-19.2.5"
      (sources."react-devtools-core-6.1.5" // {
        dependencies = [
          sources."ws-7.5.10"
        ];
      })
      sources."react-dom-19.2.5"
      sources."react-reconciler-0.33.0"
      sources."restore-cursor-4.0.0"
      sources."scheduler-0.27.0"
      sources."shell-quote-1.8.3"
      sources."signal-exit-3.0.7"
      sources."slice-ansi-8.0.0"
      sources."stack-utils-2.0.6"
      sources."string-width-8.2.0"
      sources."strip-ansi-7.2.0"
      sources."tagged-tag-1.0.0"
      sources."terminal-size-4.0.1"
      sources."to-rotated-1.0.0"
      sources."type-fest-5.5.0"
      sources."widest-line-6.0.0"
      (sources."wrap-ansi-9.0.2" // {
        dependencies = [
          sources."string-width-7.2.0"
        ];
      })
      sources."ws-8.20.0"
      sources."yoga-layout-3.2.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "TUI application for managing multiple Claude Code sessions across Git worktrees";
      homepage = "https://github.com/kbwo/ccmanager#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  vde-monitor = nodeEnv.buildNodePackage {
    name = "vde-monitor";
    packageName = "vde-monitor";
    version = "0.9.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/vde-monitor/-/vde-monitor-0.9.2.tgz";
      sha512 = "OIwNUwT1pqQGA6lPVu0+M5ouPhDuEZJU0SDd96LGGHH/2xmLgYIjLzUXwVisviBcUJyUuZ4FH9zwS3BiHR4uPg==";
    };
    dependencies = [
      sources."@hono/node-server-1.19.14"
      sources."@hono/zod-validator-0.7.6"
      sources."@sec-ant/readable-stream-0.4.1"
      sources."@sindresorhus/merge-streams-4.0.0"
      sources."agent-base-7.1.4"
      sources."asn1.js-5.4.1"
      sources."bn.js-4.12.3"
      sources."buffer-equal-constant-time-1.0.1"
      sources."cross-spawn-7.0.6"
      sources."debug-4.4.3"
      sources."ecdsa-sig-formatter-1.0.11"
      sources."execa-9.6.1"
      sources."figures-6.1.0"
      sources."get-stream-9.0.1"
      sources."hono-4.12.14"
      sources."http_ece-1.2.0"
      sources."https-proxy-agent-7.0.6"
      sources."human-signals-8.0.1"
      sources."inherits-2.0.4"
      sources."is-plain-obj-4.1.0"
      sources."is-stream-4.0.1"
      sources."is-unicode-supported-2.1.0"
      sources."isexe-2.0.0"
      sources."jwa-2.0.1"
      sources."jws-4.0.1"
      sources."minimalistic-assert-1.0.1"
      sources."minimist-1.2.8"
      sources."ms-2.1.3"
      (sources."npm-run-path-6.0.0" // {
        dependencies = [
          sources."path-key-4.0.0"
        ];
      })
      sources."parse-ms-4.0.0"
      sources."path-key-3.1.1"
      sources."pretty-ms-9.3.0"
      sources."qrcode-terminal-0.12.0"
      sources."safe-buffer-5.2.1"
      sources."safer-buffer-2.1.2"
      sources."shebang-command-2.0.0"
      sources."shebang-regex-3.0.0"
      sources."signal-exit-4.1.0"
      sources."strip-final-newline-4.0.0"
      sources."unicorn-magic-0.3.0"
      sources."web-push-3.6.7"
      sources."which-2.0.2"
      sources."yaml-2.8.3"
      sources."yoctocolors-2.1.2"
      sources."zod-4.3.6"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Monitor tmux sessions with a web UI.";
      homepage = "https://github.com/yuki-yano/vde-monitor#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
