# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@alcalzone/ansi-tokenize-0.2.5" = {
      name = "_at_alcalzone_slash_ansi-tokenize";
      packageName = "@alcalzone/ansi-tokenize";
      version = "0.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@alcalzone/ansi-tokenize/-/ansi-tokenize-0.2.5.tgz";
        sha512 = "3NX/MpTdroi0aKz134A6RC2Gb2iXVECN4QaAXnvCIxxIm3C3AVB1mkUe8NaaiyvOpDfsrqWhYtj+Q6a62RrTsw==";
      };
    };
    "@babel/helper-string-parser-7.27.1" = {
      name = "_at_babel_slash_helper-string-parser";
      packageName = "@babel/helper-string-parser";
      version = "7.27.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-string-parser/-/helper-string-parser-7.27.1.tgz";
        sha512 = "qMlSxKbpRlAridDExk92nSobyDdpPijUq2DW6oDnUqd0iOGxmQjyqhMIihI9+zv4LPyZdRje2cavWPbCbWm3eA==";
      };
    };
    "@babel/helper-validator-identifier-7.28.5" = {
      name = "_at_babel_slash_helper-validator-identifier";
      packageName = "@babel/helper-validator-identifier";
      version = "7.28.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-validator-identifier/-/helper-validator-identifier-7.28.5.tgz";
        sha512 = "qSs4ifwzKJSV39ucNjsvc6WVHs6b7S03sOh2OcHF9UHfVPqWWALUsNUVzhSBiItjRZoLHx7nIarVjqKVusUZ1Q==";
      };
    };
    "@babel/parser-7.29.0" = {
      name = "_at_babel_slash_parser";
      packageName = "@babel/parser";
      version = "7.29.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/parser/-/parser-7.29.0.tgz";
        sha512 = "IyDgFV5GeDUVX4YdF/3CPULtVGSXXMLh1xVIgdCgxApktqnQV0r7/8Nqthg+8YLGaAtdyIlo2qIdZrbCv4+7ww==";
      };
    };
    "@babel/types-7.29.0" = {
      name = "_at_babel_slash_types";
      packageName = "@babel/types";
      version = "7.29.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/types/-/types-7.29.0.tgz";
        sha512 = "LwdZHpScM4Qz8Xw2iKSzS+cfglZzJGvofQICy7W7v4caru4EaAmyUuO6BGrbyQ2mYV11W0U8j5mBhd14dd3B0A==";
      };
    };
    "@emmetio/abbreviation-2.3.3" = {
      name = "_at_emmetio_slash_abbreviation";
      packageName = "@emmetio/abbreviation";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emmetio/abbreviation/-/abbreviation-2.3.3.tgz";
        sha512 = "mgv58UrU3rh4YgbE/TzgLQwJ3pFsHHhCLqY20aJq+9comytTXUDNGG/SMtSeMJdkpxgXSXunBGLD8Boka3JyVA==";
      };
    };
    "@emmetio/css-abbreviation-2.1.8" = {
      name = "_at_emmetio_slash_css-abbreviation";
      packageName = "@emmetio/css-abbreviation";
      version = "2.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emmetio/css-abbreviation/-/css-abbreviation-2.1.8.tgz";
        sha512 = "s9yjhJ6saOO/uk1V74eifykk2CBYi01STTK3WlXWGOepyKa23ymJ053+DNQjpFcy1ingpaO7AxCcwLvHFY9tuw==";
      };
    };
    "@emmetio/css-parser-0.4.1" = {
      name = "_at_emmetio_slash_css-parser";
      packageName = "@emmetio/css-parser";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emmetio/css-parser/-/css-parser-0.4.1.tgz";
        sha512 = "2bC6m0MV/voF4CTZiAbG5MWKbq5EBmDPKu9Sb7s7nVcEzNQlrZP6mFFFlIaISM8X6514H9shWMme1fCm8cWAfQ==";
      };
    };
    "@emmetio/html-matcher-1.3.0" = {
      name = "_at_emmetio_slash_html-matcher";
      packageName = "@emmetio/html-matcher";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emmetio/html-matcher/-/html-matcher-1.3.0.tgz";
        sha512 = "NTbsvppE5eVyBMuyGfVu2CRrLvo7J4YHb6t9sBFLyY03WYhXET37qA4zOYUjBWFCRHO7pS1B9khERtY0f5JXPQ==";
      };
    };
    "@emmetio/scanner-1.0.4" = {
      name = "_at_emmetio_slash_scanner";
      packageName = "@emmetio/scanner";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emmetio/scanner/-/scanner-1.0.4.tgz";
        sha512 = "IqRuJtQff7YHHBk4G8YZ45uB9BaAGcwQeVzgj/zj8/UdOhtQpEIupUhSk8dys6spFIWVZVeK20CzGEnqR5SbqA==";
      };
    };
    "@emmetio/stream-reader-2.2.0" = {
      name = "_at_emmetio_slash_stream-reader";
      packageName = "@emmetio/stream-reader";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emmetio/stream-reader/-/stream-reader-2.2.0.tgz";
        sha512 = "fXVXEyFA5Yv3M3n8sUGT7+fvecGrZP4k6FnWWMSZVQf69kAq0LLpaBQLGcPR30m3zMmKYhECP4k/ZkzvhEW5kw==";
      };
    };
    "@emmetio/stream-reader-utils-0.1.0" = {
      name = "_at_emmetio_slash_stream-reader-utils";
      packageName = "@emmetio/stream-reader-utils";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emmetio/stream-reader-utils/-/stream-reader-utils-0.1.0.tgz";
        sha512 = "ZsZ2I9Vzso3Ho/pjZFsmmZ++FWeEd/txqybHTm4OgaZzdS8V9V/YYWQwg5TC38Z7uLWUV1vavpLLbjJtKubR1A==";
      };
    };
    "@johnsoncodehk/pug-beautify-0.2.2" = {
      name = "_at_johnsoncodehk_slash_pug-beautify";
      packageName = "@johnsoncodehk/pug-beautify";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@johnsoncodehk/pug-beautify/-/pug-beautify-0.2.2.tgz";
        sha512 = "qqNS/YD0Nck5wtQLCPHAfGVgWbbGafxSPjNh0ekYPFSNNqnDH2kamnduzYly8IiADmeVx/MfAE1njMEjVeHTMA==";
      };
    };
    "@standard-schema/spec-1.1.0" = {
      name = "_at_standard-schema_slash_spec";
      packageName = "@standard-schema/spec";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@standard-schema/spec/-/spec-1.1.0.tgz";
        sha512 = "l2aFy5jALhniG5HgqrD6jXLi/rUWrKvqN/qJx6yoJsgKhblVd+iqqU4RCXavm/jPityDo5TCvKMnpjKnOriy0w==";
      };
    };
    "@types/react-19.2.14" = {
      name = "_at_types_slash_react";
      packageName = "@types/react";
      version = "19.2.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/react/-/react-19.2.14.tgz";
        sha512 = "ilcTH/UniCkMdtexkoCN0bI7pMcJDvmQFPvuPvmEaYA/NSfFTAgdUSLAoVjaRJm7+6PvcM+q1zYOwS4wTYMF9w==";
      };
    };
    "@volar/language-core-2.4.27" = {
      name = "_at_volar_slash_language-core";
      packageName = "@volar/language-core";
      version = "2.4.27";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/language-core/-/language-core-2.4.27.tgz";
        sha512 = "DjmjBWZ4tJKxfNC1F6HyYERNHPYS7L7OPFyCrestykNdUZMFYzI9WTyvwPcaNaHlrEUwESHYsfEw3isInncZxQ==";
      };
    };
    "@volar/language-server-2.4.27" = {
      name = "_at_volar_slash_language-server";
      packageName = "@volar/language-server";
      version = "2.4.27";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/language-server/-/language-server-2.4.27.tgz";
        sha512 = "SymGNkErcHg8GjiG65iQN8sLkhqu1pwKhFySmxeBuYq5xFYagKBW36eiNITXQTdvT0tutI1GXcXdq/FdE/IyjA==";
      };
    };
    "@volar/language-service-2.4.27" = {
      name = "_at_volar_slash_language-service";
      packageName = "@volar/language-service";
      version = "2.4.27";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/language-service/-/language-service-2.4.27.tgz";
        sha512 = "SxKZ8yLhpWa7Y5e/RDxtNfm7j7xsXp/uf2urijXEffRNpPSmVdfzQrFFy5d7l8PNpZy+bHg+yakmqBPjQN+MOw==";
      };
    };
    "@volar/source-map-2.4.27" = {
      name = "_at_volar_slash_source-map";
      packageName = "@volar/source-map";
      version = "2.4.27";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/source-map/-/source-map-2.4.27.tgz";
        sha512 = "ynlcBReMgOZj2i6po+qVswtDUeeBRCTgDurjMGShbm8WYZgJ0PA4RmtebBJ0BCYol1qPv3GQF6jK7C9qoVc7lg==";
      };
    };
    "@volar/typescript-2.4.27" = {
      name = "_at_volar_slash_typescript";
      packageName = "@volar/typescript";
      version = "2.4.27";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/typescript/-/typescript-2.4.27.tgz";
        sha512 = "eWaYCcl/uAPInSK2Lze6IqVWaBu/itVqR5InXcHXFyles4zO++Mglt3oxdgj75BDcv1Knr9Y93nowS8U3wqhxg==";
      };
    };
    "@vscode/emmet-helper-2.11.0" = {
      name = "_at_vscode_slash_emmet-helper";
      packageName = "@vscode/emmet-helper";
      version = "2.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vscode/emmet-helper/-/emmet-helper-2.11.0.tgz";
        sha512 = "QLxjQR3imPZPQltfbWRnHU6JecWTF1QSWhx3GAKQpslx7y3Dp6sIIXhKjiUJ/BR9FX8PVthjr9PD6pNwOJfAzw==";
      };
    };
    "@vscode/l10n-0.0.18" = {
      name = "_at_vscode_slash_l10n";
      packageName = "@vscode/l10n";
      version = "0.0.18";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vscode/l10n/-/l10n-0.0.18.tgz";
        sha512 = "KYSIHVmslkaCDyw013pphY+d7x1qV8IZupYfeIfzNA+nsaWHbn5uPuQRvdRFsa9zFzGeudPuoGoZ1Op4jrJXIQ==";
      };
    };
    "@vue/compiler-core-3.5.28" = {
      name = "_at_vue_slash_compiler-core";
      packageName = "@vue/compiler-core";
      version = "3.5.28";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/compiler-core/-/compiler-core-3.5.28.tgz";
        sha512 = "kviccYxTgoE8n6OCw96BNdYlBg2GOWfBuOW4Vqwrt7mSKWKwFVvI8egdTltqRgITGPsTFYtKYfxIG8ptX2PJHQ==";
      };
    };
    "@vue/compiler-dom-3.5.28" = {
      name = "_at_vue_slash_compiler-dom";
      packageName = "@vue/compiler-dom";
      version = "3.5.28";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/compiler-dom/-/compiler-dom-3.5.28.tgz";
        sha512 = "/1ZepxAb159jKR1btkefDP+J2xuWL5V3WtleRmxaT+K2Aqiek/Ab/+Ebrw2pPj0sdHO8ViAyyJWfhXXOP/+LQA==";
      };
    };
    "@vue/language-core-3.2.4" = {
      name = "_at_vue_slash_language-core";
      packageName = "@vue/language-core";
      version = "3.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/language-core/-/language-core-3.2.4.tgz";
        sha512 = "bqBGuSG4KZM45KKTXzGtoCl9cWju5jsaBKaJJe3h5hRAAWpZUuj5G+L+eI01sPIkm4H6setKRlw7E85wLdDNew==";
      };
    };
    "@vue/language-service-3.2.4" = {
      name = "_at_vue_slash_language-service";
      packageName = "@vue/language-service";
      version = "3.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/language-service/-/language-service-3.2.4.tgz";
        sha512 = "sY5+XQxmsBNeWnUBtbnubtv6wYdlxFURAjUSetUqaG0f0uYjqVnQ+4kITMHork+9HaV3zKmCY5zOf5psGW/Xkw==";
      };
    };
    "@vue/shared-3.5.28" = {
      name = "_at_vue_slash_shared";
      packageName = "@vue/shared";
      version = "3.5.28";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/shared/-/shared-3.5.28.tgz";
        sha512 = "cfWa1fCGBxrvaHRhvV3Is0MgmrbSCxYTXCSCau2I0a1Xw1N1pHAvkWCiXPRAqjvToILvguNyEwjevUqAuBQWvQ==";
      };
    };
    "@vue/typescript-plugin-3.2.4" = {
      name = "_at_vue_slash_typescript-plugin";
      packageName = "@vue/typescript-plugin";
      version = "3.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/typescript-plugin/-/typescript-plugin-3.2.4.tgz";
        sha512 = "K/rKnIQre0X6YyKSbDW+DEYpVkOBrB0ScXus0nvtjI7zwo+0FE+wxUXAXeKtaQwJzQ0d8Pw2FPa0mcZhYpMQug==";
      };
    };
    "@xterm/headless-6.0.0" = {
      name = "_at_xterm_slash_headless";
      packageName = "@xterm/headless";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@xterm/headless/-/headless-6.0.0.tgz";
        sha512 = "5Yj1QINYCyzrZtf8OFIHi47iQtI+0qYFPHmouEfG8dHNxbZ9Tb9YGSuLcsEwj9Z+OL75GJqPyJbyoFer80a2Hw==";
      };
    };
    "acorn-7.4.1" = {
      name = "acorn";
      packageName = "acorn";
      version = "7.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-7.4.1.tgz";
        sha512 = "nQyp0o1/mNdbTO1PO6kHkwSrmgZ0MT/jCCpNiwbUjGoRN4dlBhqJtoQuCnEOKzgTVwg0ZWiCoQy6SxMebQVh8A==";
      };
    };
    "alien-signals-3.1.2" = {
      name = "alien-signals";
      packageName = "alien-signals";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/alien-signals/-/alien-signals-3.1.2.tgz";
        sha512 = "d9dYqZTS90WLiU0I5c6DHj/HcKkF8ZyGN3G5x8wSbslulz70KOxaqCT0hQCo9KOyhVqzqGojvNdJXoTumZOtcw==";
      };
    };
    "ansi-escapes-7.3.0" = {
      name = "ansi-escapes";
      packageName = "ansi-escapes";
      version = "7.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-escapes/-/ansi-escapes-7.3.0.tgz";
        sha512 = "BvU8nYgGQBxcmMuEeUEmNTvrMVjJNSH7RgW24vXexN4Ven6qCvy4TntnvlnwnMLTVlcRQQdbRY8NKnaIoeWDNg==";
      };
    };
    "ansi-regex-6.2.2" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "6.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-6.2.2.tgz";
        sha512 = "Bq3SmSpyFHaWjPk8If9yc6svM8c56dB5BAtW4Qbw5jHTwwXXcTLoRMkpDJp6VL0XzlWaCHTXrkFURMYmD0sLqg==";
      };
    };
    "ansi-styles-6.2.3" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "6.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-6.2.3.tgz";
        sha512 = "4Dj6M28JB+oAH8kFkTLUo+a2jwOFkuqb3yucU0CANcRRUbxS0cP0nZYCGjcc3BNXwRIsUVmDGgzawme7zvJHvg==";
      };
    };
    "async-function-1.0.0" = {
      name = "async-function";
      packageName = "async-function";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/async-function/-/async-function-1.0.0.tgz";
        sha512 = "hsU18Ae8CDTR6Kgu9DYf0EbCr/a5iGL0rytQDobUcdpYOKokk8LEjVphnXkDkgpi0wYVsqrXuP0bZxJaTqdgoA==";
      };
    };
    "async-generator-function-1.0.0" = {
      name = "async-generator-function";
      packageName = "async-generator-function";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/async-generator-function/-/async-generator-function-1.0.0.tgz";
        sha512 = "+NAXNqgCrB95ya4Sr66i1CL2hqLVckAk7xwRYWdcm39/ELQ6YNn1aw5r0bdQtqNZgQpEWzc5yc/igXc7aL5SLA==";
      };
    };
    "auto-bind-5.0.1" = {
      name = "auto-bind";
      packageName = "auto-bind";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/auto-bind/-/auto-bind-5.0.1.tgz";
        sha512 = "ooviqdwwgfIfNmDwo94wlshcdzfO64XV0Cg6oDsDYBJfITDz1EngD2z7DkbvCWn+XIMsIqW27sEVF6qcpJrRcg==";
      };
    };
    "bufferutil-4.1.0" = {
      name = "bufferutil";
      packageName = "bufferutil";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bufferutil/-/bufferutil-4.1.0.tgz";
        sha512 = "ZMANVnAixE6AWWnPzlW2KpUrxhm9woycYvPOo67jWHyFowASTEd9s+QN1EIMsSDtwhIxN4sWE1jotpuDUIgyIw==";
      };
    };
    "call-bind-apply-helpers-1.0.2" = {
      name = "call-bind-apply-helpers";
      packageName = "call-bind-apply-helpers";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/call-bind-apply-helpers/-/call-bind-apply-helpers-1.0.2.tgz";
        sha512 = "Sp1ablJ0ivDkSzjcaJdxEunN5/XvksFJ2sMBFfq6x0ryhQV/2b/KwFe21cMpmHtPOSij8K99/wSfoEuTObmuMQ==";
      };
    };
    "call-bound-1.0.4" = {
      name = "call-bound";
      packageName = "call-bound";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/call-bound/-/call-bound-1.0.4.tgz";
        sha512 = "+ys997U96po4Kx/ABpBCqhA9EuxJaQWDQg7295H4hBphv3IZg0boBKuwYpt4YXp6MZ5AmZQnU/tyMTlRpaSejg==";
      };
    };
    "chalk-5.6.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "5.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-5.6.2.tgz";
        sha512 = "7NzBL0rN6fMUW+f7A6Io4h40qQlG+xGmtMxfbnH/K7TAtt8JQWVQK+6g0UXKMeVJoyV5EkkNsErQ8pVD3bLHbA==";
      };
    };
    "character-parser-2.2.0" = {
      name = "character-parser";
      packageName = "character-parser";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/character-parser/-/character-parser-2.2.0.tgz";
        sha512 = "+UqJQjFEFaTAs3bNsF2j2kEN1baG/zghZbdqoYEDxGZtJo9LBzl1A+m0D4n3qKx8N2FNv8/Xp6yV9mQmBuptaw==";
      };
    };
    "cli-boxes-3.0.0" = {
      name = "cli-boxes";
      packageName = "cli-boxes";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-boxes/-/cli-boxes-3.0.0.tgz";
        sha512 = "/lzGpEWL/8PfI0BmBOPRwp0c/wFNX1RdUML3jK/RcSBA9T8mZDdQpqYBKtCFTOfQbwPqWEOpjqW+Fnayc0969g==";
      };
    };
    "cli-cursor-4.0.0" = {
      name = "cli-cursor";
      packageName = "cli-cursor";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-cursor/-/cli-cursor-4.0.0.tgz";
        sha512 = "VGtlMu3x/4DOtIUwEkRezxUZ2lBacNJCHash0N0WeZDBS+7Ux1dm3XWAgWYxLJFMMdOeXMHXorshEFhbMSGelg==";
      };
    };
    "cli-truncate-5.1.1" = {
      name = "cli-truncate";
      packageName = "cli-truncate";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-truncate/-/cli-truncate-5.1.1.tgz";
        sha512 = "SroPvNHxUnk+vIW/dOSfNqdy1sPEFkrTk6TUtqLCnBlo3N7TNYYkzzN7uSD6+jVjrdO4+p8nH7JzH6cIvUem6A==";
      };
    };
    "code-excerpt-4.0.0" = {
      name = "code-excerpt";
      packageName = "code-excerpt";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/code-excerpt/-/code-excerpt-4.0.0.tgz";
        sha512 = "xxodCmBen3iy2i0WtAK8FlFNrRzjUqjRsMfho58xT/wvZU1YTM3fCnRjcy1gJPMepaRlgm/0e6w8SpWHpn3/cA==";
      };
    };
    "convert-to-spaces-2.0.1" = {
      name = "convert-to-spaces";
      packageName = "convert-to-spaces";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/convert-to-spaces/-/convert-to-spaces-2.0.1.tgz";
        sha512 = "rcQ1bsQO9799wq24uE5AM2tAILy4gXGIK/njFWcVQkGNZ96edlpY+A7bjwvzjYvLDyzmG1MmMLZhpcsb+klNMQ==";
      };
    };
    "csstype-3.2.3" = {
      name = "csstype";
      packageName = "csstype";
      version = "3.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/csstype/-/csstype-3.2.3.tgz";
        sha512 = "z1HGKcYy2xA8AGQfwrn0PAy+PB7X/GSj3UVJW9qKyn43xWa+gl5nXmU4qqLMRzWVLFC8KusUX8T/0kCiOYpAIQ==";
      };
    };
    "dunder-proto-1.0.1" = {
      name = "dunder-proto";
      packageName = "dunder-proto";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dunder-proto/-/dunder-proto-1.0.1.tgz";
        sha512 = "KIN/nDJBQRcXw0MLVhZE9iQHmG68qAVIBg9CqmUYjmQIhgij9U5MFvrqkUL5FbtyyzZuOeOt0zdeRe4UY7ct+A==";
      };
    };
    "effect-3.19.18" = {
      name = "effect";
      packageName = "effect";
      version = "3.19.18";
      src = fetchurl {
        url = "https://registry.npmjs.org/effect/-/effect-3.19.18.tgz";
        sha512 = "KlbNuYzzwpOpnpshIhjCaqweQkthAT1oVG61Z2wIHqo6Sb6n/+pgzFXyTvsLyxcx5Cg3aWaQXa0XQHMuzdVW4A==";
      };
    };
    "emmet-2.4.11" = {
      name = "emmet";
      packageName = "emmet";
      version = "2.4.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/emmet/-/emmet-2.4.11.tgz";
        sha512 = "23QPJB3moh/U9sT4rQzGgeyyGIrcM+GH5uVYg2C6wZIxAIJq7Ng3QLT79tl8FUwDXhyq9SusfknOrofAKqvgyQ==";
      };
    };
    "emoji-regex-10.6.0" = {
      name = "emoji-regex";
      packageName = "emoji-regex";
      version = "10.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-10.6.0.tgz";
        sha512 = "toUI84YS5YmxW219erniWD0CIVOo46xGKColeNQRgOzDorgBi1v4D71/OFzgD9GO2UGKIv1C3Sp8DAn0+j5w7A==";
      };
    };
    "entities-7.0.1" = {
      name = "entities";
      packageName = "entities";
      version = "7.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-7.0.1.tgz";
        sha512 = "TWrgLOFUQTH994YUyl1yT4uyavY5nNB5muff+RtWaqNVCAK408b5ZnnbNAUEWLTCpum9w6arT70i1XdQ4UeOPA==";
      };
    };
    "environment-1.1.0" = {
      name = "environment";
      packageName = "environment";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/environment/-/environment-1.1.0.tgz";
        sha512 = "xUtoPkMggbz0MPyPiIWr1Kp4aeWJjDZ6SMvURhimjdZgsRuDplF5/s9hcgGhyXMhs+6vpnuoiZ2kFiu3FMnS8Q==";
      };
    };
    "es-define-property-1.0.1" = {
      name = "es-define-property";
      packageName = "es-define-property";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-define-property/-/es-define-property-1.0.1.tgz";
        sha512 = "e3nRfgfUZ4rNGL232gUgX06QNyyez04KdjFrF+LTRoOXmrOgFKDg4BCdsjW8EnT69eqdYGmRpJwiPVYNrCaW3g==";
      };
    };
    "es-errors-1.3.0" = {
      name = "es-errors";
      packageName = "es-errors";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-errors/-/es-errors-1.3.0.tgz";
        sha512 = "Zf5H2Kxt2xjTvbJvP2ZWLEICxA6j+hAmMzIlypy4xcBg1vKVnx89Wy0GbS+kf5cwCVFFzdCFh2XSCFNULS6csw==";
      };
    };
    "es-object-atoms-1.1.1" = {
      name = "es-object-atoms";
      packageName = "es-object-atoms";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-object-atoms/-/es-object-atoms-1.1.1.tgz";
        sha512 = "FGgH2h8zKNim9ljj7dankFPcICIK9Cp5bm+c2gQSYePhpaG5+esrLODihIorn+Pe6FGJzWhXQotPv73jTaldXA==";
      };
    };
    "es-toolkit-1.44.0" = {
      name = "es-toolkit";
      packageName = "es-toolkit";
      version = "1.44.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-toolkit/-/es-toolkit-1.44.0.tgz";
        sha512 = "6penXeZalaV88MM3cGkFZZfOoLGWshWWfdy0tWw/RlVVyhvMaWSBTOvXNeiW3e5FwdS5ePW0LGEu17zT139ktg==";
      };
    };
    "escape-string-regexp-2.0.0" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-2.0.0.tgz";
        sha512 = "UpzcLCXolUWcNu5HtVMHYdXJjArjsF9C0aNnquZYY4uW/Vu0miy5YoWvbV345HauVvcAUnpRuhMMcqTcGOY2+w==";
      };
    };
    "estree-walker-2.0.2" = {
      name = "estree-walker";
      packageName = "estree-walker";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/estree-walker/-/estree-walker-2.0.2.tgz";
        sha512 = "Rfkk/Mp/DL7JVje3u18FxFujQlTNR2q6QfMSMB7AvCBx91NGj/ba3kCfza0f6dVDbw7YlRf/nDrn7pQrCCyQ/w==";
      };
    };
    "fast-check-3.23.2" = {
      name = "fast-check";
      packageName = "fast-check";
      version = "3.23.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-check/-/fast-check-3.23.2.tgz";
        sha512 = "h5+1OzzfCC3Ef7VbtKdcv7zsstUQwUDlYpUTvjeUsJAssPgLn7QzbboPtL5ro04Mq0rPOsMzl7q5hIbRs2wD1A==";
      };
    };
    "figures-6.1.0" = {
      name = "figures";
      packageName = "figures";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/figures/-/figures-6.1.0.tgz";
        sha512 = "d+l3qxjSesT4V7v2fh+QnmFnUWv9lSpjarhShNTgBOfA0ttejbQUAlHLitbjkoRiDulW0OPoQPYIGhIC8ohejg==";
      };
    };
    "function-bind-1.1.2" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.2.tgz";
        sha512 = "7XHNxH7qX9xG5mIwxkhumTox/MIRNcOgDrxWsMt2pAr23WHp6MrRlN7FBSFpCpr+oVO0F744iUgR82nJMfG2SA==";
      };
    };
    "generator-function-2.0.1" = {
      name = "generator-function";
      packageName = "generator-function";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/generator-function/-/generator-function-2.0.1.tgz";
        sha512 = "SFdFmIJi+ybC0vjlHN0ZGVGHc3lgE0DxPAT0djjVg+kjOnSqclqmj0KQ7ykTOLP6YxoqOvuAODGdcHJn+43q3g==";
      };
    };
    "get-east-asian-width-1.4.0" = {
      name = "get-east-asian-width";
      packageName = "get-east-asian-width";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-east-asian-width/-/get-east-asian-width-1.4.0.tgz";
        sha512 = "QZjmEOC+IT1uk6Rx0sX22V6uHWVwbdbxf1faPqJ1QhLdGgsRGCZoyaQBm/piRdJy/D2um6hM1UP7ZEeQ4EkP+Q==";
      };
    };
    "get-intrinsic-1.3.1" = {
      name = "get-intrinsic";
      packageName = "get-intrinsic";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-intrinsic/-/get-intrinsic-1.3.1.tgz";
        sha512 = "fk1ZVEeOX9hVZ6QzoBNEC55+Ucqg4sTVwrVuigZhuRPESVFpMyXnd3sbXvPOwp7Y9riVyANiqhEuRF0G1aVSeQ==";
      };
    };
    "get-proto-1.0.1" = {
      name = "get-proto";
      packageName = "get-proto";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-proto/-/get-proto-1.0.1.tgz";
        sha512 = "sTSfBjoXBp89JvIKIefqw7U2CCebsc74kiY6awiGogKtoSGbgjYE/G/+l9sF3MWFPNc9IcoOC4ODfKHfxFmp0g==";
      };
    };
    "gopd-1.2.0" = {
      name = "gopd";
      packageName = "gopd";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/gopd/-/gopd-1.2.0.tgz";
        sha512 = "ZUKRh6/kUFoAiTAtTYPZJ3hw9wNxx+BIBOijnlG9PnrJsCcSjs1wyyD6vJpaYtgnzDrKYRSqf3OO6Rfa93xsRg==";
      };
    };
    "has-symbols-1.1.0" = {
      name = "has-symbols";
      packageName = "has-symbols";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-symbols/-/has-symbols-1.1.0.tgz";
        sha512 = "1cDNdwJ2Jaohmb3sg4OmKaMBwuC48sYni5HUw2DvsC8LjGTLK9h+eb1X6RyuOHe4hT0ULCW68iomhjUoKUqlPQ==";
      };
    };
    "has-tostringtag-1.0.2" = {
      name = "has-tostringtag";
      packageName = "has-tostringtag";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-tostringtag/-/has-tostringtag-1.0.2.tgz";
        sha512 = "NqADB8VjPFLM2V0VvHUewwwsw0ZWBaIdgo+ieHtK3hasLz4qeCRjYcqfB6AQrBggRKppKF8L52/VqdVsO47Dlw==";
      };
    };
    "hasown-2.0.2" = {
      name = "hasown";
      packageName = "hasown";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/hasown/-/hasown-2.0.2.tgz";
        sha512 = "0hJU9SCPvmMzIBdZFqNPXWa6dqh7WdH0cII9y+CyS8rG3nL48Bclra9HmKhVVUHyPWNH5Y7xDwAB7bfgSjkUMQ==";
      };
    };
    "indent-string-5.0.0" = {
      name = "indent-string";
      packageName = "indent-string";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/indent-string/-/indent-string-5.0.0.tgz";
        sha512 = "m6FAo/spmsW2Ab2fU35JTYwtOKa2yAwXSwgjSv1TJzh4Mh7mC3lzAOVLBprb72XsTrgkEIsl7YrFNAiDiRhIGg==";
      };
    };
    "ink-6.7.0" = {
      name = "ink";
      packageName = "ink";
      version = "6.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ink/-/ink-6.7.0.tgz";
        sha512 = "dhB16KfdTO8yYwF2K0E4wPXpL88tdrjjB6w44AZ0ljSktYoUQQcxccq9KL1vpRhk8JIa0A7B7zvjajHqI42teA==";
      };
    };
    "ink-select-input-6.2.0" = {
      name = "ink-select-input";
      packageName = "ink-select-input";
      version = "6.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ink-select-input/-/ink-select-input-6.2.0.tgz";
        sha512 = "304fZXxkpYxJ9si5lxRCaX01GNlmPBgOZumXXRnPYbHW/iI31cgQynqk2tRypGLOF1cMIwPUzL2LSm6q4I5rQQ==";
      };
    };
    "ink-text-input-6.0.0" = {
      name = "ink-text-input";
      packageName = "ink-text-input";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ink-text-input/-/ink-text-input-6.0.0.tgz";
        sha512 = "Fw64n7Yha5deb1rHY137zHTAbSTNelUKuB5Kkk2HACXEtwIHBCf9OH2tP/LQ9fRYTl1F0dZgbW0zPnZk6FA9Lw==";
      };
    };
    "is-expression-4.0.0" = {
      name = "is-expression";
      packageName = "is-expression";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-expression/-/is-expression-4.0.0.tgz";
        sha512 = "zMIXX63sxzG3XrkHkrAPvm/OVZVSCPNkwMHU8oTX7/U3AL78I0QXCEICXUM13BIa8TYGZ68PiTKfQz3yaTNr4A==";
      };
    };
    "is-fullwidth-code-point-5.1.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-5.1.0.tgz";
        sha512 = "5XHYaSyiqADb4RnZ1Bdad6cPp8Toise4TzEjcOYDHZkTCbKgiUl7WTUCpNWHuxmDt91wnsZBc9xinNzopv3JMQ==";
      };
    };
    "is-in-ci-2.0.0" = {
      name = "is-in-ci";
      packageName = "is-in-ci";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-in-ci/-/is-in-ci-2.0.0.tgz";
        sha512 = "cFeerHriAnhrQSbpAxL37W1wcJKUUX07HyLWZCW1URJT/ra3GyUTzBgUnh24TMVfNTV2Hij2HLxkPHFZfOZy5w==";
      };
    };
    "is-regex-1.2.1" = {
      name = "is-regex";
      packageName = "is-regex";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-regex/-/is-regex-1.2.1.tgz";
        sha512 = "MjYsKHO5O7mCsmRGxWcLWheFqN9DJ/2TmngvjKXihe6efViPqc274+Fx/4fYj/r03+ESvBdTXK0V6tA3rgez1g==";
      };
    };
    "is-unicode-supported-2.1.0" = {
      name = "is-unicode-supported";
      packageName = "is-unicode-supported";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-unicode-supported/-/is-unicode-supported-2.1.0.tgz";
        sha512 = "mE00Gnza5EEB3Ds0HfMyllZzbBrmLOX3vfWoj9A9PEnTfratQ/BcaJOuMhnkhjXvb2+FkY3VuHqtAGpTPmglFQ==";
      };
    };
    "jsonc-parser-2.3.1" = {
      name = "jsonc-parser";
      packageName = "jsonc-parser";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonc-parser/-/jsonc-parser-2.3.1.tgz";
        sha512 = "H8jvkz1O50L3dMZCsLqiuB2tA7muqbSg1AtGEkN0leAqGjsUzDJir3Zwr02BhqdcITPg3ei3mZ+HjMocAknhhg==";
      };
    };
    "jsonc-parser-3.3.1" = {
      name = "jsonc-parser";
      packageName = "jsonc-parser";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonc-parser/-/jsonc-parser-3.3.1.tgz";
        sha512 = "HUgH65KyejrUFPvHFPbqOY0rsFip3Bo5wb4ngvdi1EpCYWUQDC5V+Y7mZws+DLkr4M//zQJoanu1SP+87Dv1oQ==";
      };
    };
    "math-intrinsics-1.1.0" = {
      name = "math-intrinsics";
      packageName = "math-intrinsics";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/math-intrinsics/-/math-intrinsics-1.1.0.tgz";
        sha512 = "/IXtbwEk5HTPyEwyKX6hGkYXxM9nbj64B+ilVJnC/R6B0pH5G4V3b0pVbL7DBj4tkhBAppbQUlf6F6Xl9LHu1g==";
      };
    };
    "meow-14.0.0" = {
      name = "meow";
      packageName = "meow";
      version = "14.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/meow/-/meow-14.0.0.tgz";
        sha512 = "JhC3R1f6dbspVtmF3vKjAWz1EVIvwFrGGPLSdU6rK79xBwHWTuHoLnRX/t1/zHS1Ch1Y2UtIrih7DAHuH9JFJA==";
      };
    };
    "mimic-fn-2.1.0" = {
      name = "mimic-fn";
      packageName = "mimic-fn";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-fn/-/mimic-fn-2.1.0.tgz";
        sha512 = "OqbOk5oEQeAZ8WXWydlu9HJjz9WVdEIvamMCcXmuqUYjTknH/sqsWvhQ3vgwKFRR1HpjvNBKQ37nbJgYzGqGcg==";
      };
    };
    "muggle-string-0.4.1" = {
      name = "muggle-string";
      packageName = "muggle-string";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/muggle-string/-/muggle-string-0.4.1.tgz";
        sha512 = "VNTrAak/KhO2i8dqqnqnAHOa3cYBwXEZe9h+D5h/1ZqFSTEFHdM65lR7RoIqq3tBBYavsOXV84NoHXZ0AkPyqQ==";
      };
    };
    "node-gyp-build-4.8.4" = {
      name = "node-gyp-build";
      packageName = "node-gyp-build";
      version = "4.8.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-gyp-build/-/node-gyp-build-4.8.4.tgz";
        sha512 = "LA4ZjwlnUblHVgq0oBF3Jl/6h/Nvs5fzBLwdEF4nuxnFdsfajde4WfxtJr3CaiH+F6ewcIB/q4jQ4UzPyid+CQ==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha512 = "rJgTQnkUnH1sFw8yT6VSU3zD3sWmu6sZhIseY8VX+GRu3P6F7Fu+JNDoXfklElbLJSnc3FUQHVe4cU5hj+BcUg==";
      };
    };
    "onetime-5.1.2" = {
      name = "onetime";
      packageName = "onetime";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/onetime/-/onetime-5.1.2.tgz";
        sha512 = "kbpaSSGJTWdAY5KPVeMOKXSrPtr8C8C7wodJbcsd51jRnmD+GZu8Y0VoU6Dm5Z4vWr0Ig/1NKuWRKf7j5aaYSg==";
      };
    };
    "patch-console-2.0.0" = {
      name = "patch-console";
      packageName = "patch-console";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/patch-console/-/patch-console-2.0.0.tgz";
        sha512 = "0YNdUceMdaQwoKce1gatDScmMo5pu/tfABfnzEqeG0gtTmd7mh/WcwgUjtAeOU7N8nFFlbQBnFK2gXW5fGvmMA==";
      };
    };
    "path-browserify-1.0.1" = {
      name = "path-browserify";
      packageName = "path-browserify";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-browserify/-/path-browserify-1.0.1.tgz";
        sha512 = "b7uo2UCUOYZcnF/3ID0lulOJi/bafxa1xPe7ZPsammBSpjSWQkjNxlt635YGS2MiR9GjvuXCtz2emr3jbsz98g==";
      };
    };
    "picomatch-4.0.3" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-4.0.3.tgz";
        sha512 = "5gTmgEY/sqK6gFXLIsQNH19lWb4ebPDLA4SdLP7dsWkIXHWlG66oPuVvXSGFPppYZz8ZDZq0dYYrbHfBCVUb1Q==";
      };
    };
    "pug-error-2.1.0" = {
      name = "pug-error";
      packageName = "pug-error";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-error/-/pug-error-2.1.0.tgz";
        sha512 = "lv7sU9e5Jk8IeUheHata6/UThZ7RK2jnaaNztxfPYUY+VxZyk/ePVaNZ/vwmH8WqGvDz3LrNYt/+gA55NDg6Pg==";
      };
    };
    "pug-lexer-5.0.1" = {
      name = "pug-lexer";
      packageName = "pug-lexer";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-lexer/-/pug-lexer-5.0.1.tgz";
        sha512 = "0I6C62+keXlZPZkOJeVam9aBLVP2EnbeDw3An+k0/QlqdwH6rv8284nko14Na7c0TtqtogfWXcRoFE4O4Ff20w==";
      };
    };
    "pug-parser-6.0.0" = {
      name = "pug-parser";
      packageName = "pug-parser";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-parser/-/pug-parser-6.0.0.tgz";
        sha512 = "ukiYM/9cH6Cml+AOl5kETtM9NR3WulyVP2y4HOU45DyMim1IeP/OOiyEWRr6qk5I5klpsBnbuHpwKmTx6WURnw==";
      };
    };
    "pure-rand-6.1.0" = {
      name = "pure-rand";
      packageName = "pure-rand";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pure-rand/-/pure-rand-6.1.0.tgz";
        sha512 = "bVWawvoZoBYpp6yIoQtQXHZjmz35RSVHnUOTefl8Vcjr8snTPY1wnpSPMWekcFwbxI6gtmT7rSYPFvz71ldiOA==";
      };
    };
    "react-19.2.4" = {
      name = "react";
      packageName = "react";
      version = "19.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/react/-/react-19.2.4.tgz";
        sha512 = "9nfp2hYpCwOjAN+8TZFGhtWEwgvWHXqESH8qT89AT/lWklpLON22Lc8pEtnpsZz7VmawabSU0gCjnj8aC0euHQ==";
      };
    };
    "react-devtools-core-6.1.5" = {
      name = "react-devtools-core";
      packageName = "react-devtools-core";
      version = "6.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-devtools-core/-/react-devtools-core-6.1.5.tgz";
        sha512 = "ePrwPfxAnB+7hgnEr8vpKxL9cmnp7F322t8oqcPshbIQQhDKgFDW4tjhF2wjVbdXF9O/nyuy3sQWd9JGpiLPvA==";
      };
    };
    "react-dom-19.2.4" = {
      name = "react-dom";
      packageName = "react-dom";
      version = "19.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-dom/-/react-dom-19.2.4.tgz";
        sha512 = "AXJdLo8kgMbimY95O2aKQqsz2iWi9jMgKJhRBAxECE4IFxfcazB2LmzloIoibJI3C12IlY20+KFaLv+71bUJeQ==";
      };
    };
    "react-reconciler-0.33.0" = {
      name = "react-reconciler";
      packageName = "react-reconciler";
      version = "0.33.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-reconciler/-/react-reconciler-0.33.0.tgz";
        sha512 = "KetWRytFv1epdpJc3J4G75I4WrplZE5jOL7Yq0p34+OVOKF4Se7WrdIdVC45XsSSmUTlht2FM/fM1FZb1mfQeA==";
      };
    };
    "request-light-0.7.0" = {
      name = "request-light";
      packageName = "request-light";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/request-light/-/request-light-0.7.0.tgz";
        sha512 = "lMbBMrDoxgsyO+yB3sDcrDuX85yYt7sS8BfQd11jtbW/z5ZWgLZRcEGLsLoYw7I0WSUGQBs8CC8ScIxkTX1+6Q==";
      };
    };
    "restore-cursor-4.0.0" = {
      name = "restore-cursor";
      packageName = "restore-cursor";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/restore-cursor/-/restore-cursor-4.0.0.tgz";
        sha512 = "I9fPXU9geO9bHOt9pHHOhOkYerIMsmVaWB0rA2AI9ERh/+x/i7MV5HKBNrg+ljO5eoPVgCcnFuRjJ9uH6I/3eg==";
      };
    };
    "scheduler-0.27.0" = {
      name = "scheduler";
      packageName = "scheduler";
      version = "0.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/scheduler/-/scheduler-0.27.0.tgz";
        sha512 = "eNv+WrVbKu1f3vbYJT/xtiF5syA5HPIMtf9IgY/nKg0sWqzAUEvqY/xm7OcZc/qafLx/iO9FgOmeSAp4v5ti/Q==";
      };
    };
    "semver-7.7.4" = {
      name = "semver";
      packageName = "semver";
      version = "7.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.7.4.tgz";
        sha512 = "vFKC2IEtQnVhpT78h1Yp8wzwrf8CM+MzKMHGJZfBtzhZNycRFnXsHk6E5TxIkkMsgNS7mdX3AGB7x2QM2di4lA==";
      };
    };
    "shell-quote-1.8.3" = {
      name = "shell-quote";
      packageName = "shell-quote";
      version = "1.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/shell-quote/-/shell-quote-1.8.3.tgz";
        sha512 = "ObmnIF4hXNg1BqhnHmgbDETF8dLPCggZWBjkQfhZpbszZnYur5DUljTcCHii5LC3J5E0yeO/1LIMyH+UvHQgyw==";
      };
    };
    "signal-exit-3.0.7" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.7.tgz";
        sha512 = "wnD2ZE+l+SPC/uoS0vXeE9L1+0wuaMqKlfz9AMUo38JsyLSBWSFcHR1Rri62LZc12vLr1gb3jl7iwQhgwpAbGQ==";
      };
    };
    "slice-ansi-7.1.2" = {
      name = "slice-ansi";
      packageName = "slice-ansi";
      version = "7.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/slice-ansi/-/slice-ansi-7.1.2.tgz";
        sha512 = "iOBWFgUX7caIZiuutICxVgX1SdxwAVFFKwt1EvMYYec/NWO5meOJ6K5uQxhrYBdQJne4KxiqZc+KptFOWFSI9w==";
      };
    };
    "source-map-js-1.2.1" = {
      name = "source-map-js";
      packageName = "source-map-js";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-js/-/source-map-js-1.2.1.tgz";
        sha512 = "UXWMKhLOwVKb728IUtQPXxfYU+usdybtUrK/8uGE8CQMvrhOpwvzDBwj0QhSL7MQc7vIsISBG8VQ8+IDQxpfQA==";
      };
    };
    "stack-utils-2.0.6" = {
      name = "stack-utils";
      packageName = "stack-utils";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/stack-utils/-/stack-utils-2.0.6.tgz";
        sha512 = "XlkWvfIm6RmsWtNJx+uqtKLS8eqFbxUg0ZzLXqY0caEy9l7hruX8IpiDnjsLavoBgqCCR71TqWO8MaXYheJ3RQ==";
      };
    };
    "string-width-7.2.0" = {
      name = "string-width";
      packageName = "string-width";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-7.2.0.tgz";
        sha512 = "tsaTIkKW9b4N+AEj+SVA+WhJzV7/zMhcSu78mLKWSk7cXMOSHsBKFWUs0fWwq8QyK3MgJBQRX6Gbi4kYbdvGkQ==";
      };
    };
    "string-width-8.1.1" = {
      name = "string-width";
      packageName = "string-width";
      version = "8.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-8.1.1.tgz";
        sha512 = "KpqHIdDL9KwYk22wEOg/VIqYbrnLeSApsKT/bSj6Ez7pn3CftUiLAv2Lccpq1ALcpLV9UX1Ppn92npZWu2w/aw==";
      };
    };
    "strip-ansi-7.1.2" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "7.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-7.1.2.tgz";
        sha512 = "gmBGslpoQJtgnMAvOVqGZpEz9dyoKTCzy2nfz/n8aIFhN/jCE/rCmcxabB6jOOHV+0WNnylOxaxBQPSvcWklhA==";
      };
    };
    "tagged-tag-1.0.0" = {
      name = "tagged-tag";
      packageName = "tagged-tag";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tagged-tag/-/tagged-tag-1.0.0.tgz";
        sha512 = "yEFYrVhod+hdNyx7g5Bnkkb0G6si8HJurOoOEgC8B/O0uXLHlaey/65KRv6cuWBNhBgHKAROVpc7QyYqE5gFng==";
      };
    };
    "terminal-size-4.0.1" = {
      name = "terminal-size";
      packageName = "terminal-size";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/terminal-size/-/terminal-size-4.0.1.tgz";
        sha512 = "avMLDQpUI9I5XFrklECw1ZEUPJhqzcwSWsyyI8blhRLT+8N1jLJWLWWYQpB2q2xthq8xDvjZPISVh53T/+CLYQ==";
      };
    };
    "to-rotated-1.0.0" = {
      name = "to-rotated";
      packageName = "to-rotated";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-rotated/-/to-rotated-1.0.0.tgz";
        sha512 = "KsEID8AfgUy+pxVRLsWp0VzCa69wxzUDZnzGbyIST/bcgcrMvTYoFBX/QORH4YApoD89EDuUovx4BTdpOn319Q==";
      };
    };
    "token-stream-1.0.0" = {
      name = "token-stream";
      packageName = "token-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/token-stream/-/token-stream-1.0.0.tgz";
        sha512 = "VSsyNPPW74RpHwR8Fc21uubwHY7wMDeJLys2IX5zJNih+OnAnaifKHo+1LHT7DAdloQ7apeaaWg8l7qnf/TnEg==";
      };
    };
    "type-fest-4.41.0" = {
      name = "type-fest";
      packageName = "type-fest";
      version = "4.41.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-fest/-/type-fest-4.41.0.tgz";
        sha512 = "TeTSQ6H5YHvpqVwBRcnLDCBnDOHWYu7IvGbHT6N8AOymcr9PJGjc1GTtiWZTYg0NCgYwvnYWEkVChQAr9bjfwA==";
      };
    };
    "type-fest-5.4.4" = {
      name = "type-fest";
      packageName = "type-fest";
      version = "5.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-fest/-/type-fest-5.4.4.tgz";
        sha512 = "JnTrzGu+zPV3aXIUhnyWJj4z/wigMsdYajGLIYakqyOW1nPllzXEJee0QQbHj+CTIQtXGlAjuK0UY+2xTyjVAw==";
      };
    };
    "typescript-5.9.3" = {
      name = "typescript";
      packageName = "typescript";
      version = "5.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript/-/typescript-5.9.3.tgz";
        sha512 = "jl1vZzPDinLr9eUt3J/t7V6FgNEw9QjvBPdysz9KfQDD41fQrC2Y4vKQdiaUpFT4bXlb1RHhLpp8wtm6M5TgSw==";
      };
    };
    "typescript-auto-import-cache-0.3.6" = {
      name = "typescript-auto-import-cache";
      packageName = "typescript-auto-import-cache";
      version = "0.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript-auto-import-cache/-/typescript-auto-import-cache-0.3.6.tgz";
        sha512 = "RpuHXrknHdVdK7wv/8ug3Fr0WNsNi5l5aB8MYYuXhq2UH5lnEB1htJ1smhtD5VeCsGr2p8mUDtd83LCQDFVgjQ==";
      };
    };
    "utf-8-validate-5.0.10" = {
      name = "utf-8-validate";
      packageName = "utf-8-validate";
      version = "5.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/utf-8-validate/-/utf-8-validate-5.0.10.tgz";
        sha512 = "Z6czzLq4u8fPOyx7TU6X3dvUZVvoJmxSQ+IcrlmagKhilxlhZgxPK6C5Jqbkw1IDUmFTM+cz9QDnnLTwDz/2gQ==";
      };
    };
    "utf-8-validate-6.0.6" = {
      name = "utf-8-validate";
      packageName = "utf-8-validate";
      version = "6.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/utf-8-validate/-/utf-8-validate-6.0.6.tgz";
        sha512 = "q3l3P9UtEEiAHcsgsqTgf9PPjctrDWoIXW3NpOHFdRDbLvu4DLIcxHangJ4RLrWkBcKjmcs/6NkerI8T/rE4LA==";
      };
    };
    "volar-service-css-0.0.68" = {
      name = "volar-service-css";
      packageName = "volar-service-css";
      version = "0.0.68";
      src = fetchurl {
        url = "https://registry.npmjs.org/volar-service-css/-/volar-service-css-0.0.68.tgz";
        sha512 = "lJSMh6f3QzZ1tdLOZOzovLX0xzAadPhx8EKwraDLPxBndLCYfoTvnNuiFFV8FARrpAlW5C0WkH+TstPaCxr00Q==";
      };
    };
    "volar-service-emmet-0.0.68" = {
      name = "volar-service-emmet";
      packageName = "volar-service-emmet";
      version = "0.0.68";
      src = fetchurl {
        url = "https://registry.npmjs.org/volar-service-emmet/-/volar-service-emmet-0.0.68.tgz";
        sha512 = "nHvixrRQ83EzkQ4G/jFxu9Y4eSsXS/X2cltEPDM+K9qZmIv+Ey1w0tg1+6caSe8TU5Hgw4oSTwNMf/6cQb3LzQ==";
      };
    };
    "volar-service-html-0.0.68" = {
      name = "volar-service-html";
      packageName = "volar-service-html";
      version = "0.0.68";
      src = fetchurl {
        url = "https://registry.npmjs.org/volar-service-html/-/volar-service-html-0.0.68.tgz";
        sha512 = "fru9gsLJxy33xAltXOh4TEdi312HP80hpuKhpYQD4O5hDnkNPEBdcQkpB+gcX0oK0VxRv1UOzcGQEUzWCVHLfA==";
      };
    };
    "volar-service-json-0.0.68" = {
      name = "volar-service-json";
      packageName = "volar-service-json";
      version = "0.0.68";
      src = fetchurl {
        url = "https://registry.npmjs.org/volar-service-json/-/volar-service-json-0.0.68.tgz";
        sha512 = "2d73Khlffwa0o6B6nA4vCyvqqTBuik1aj1i+EPC8a2UdmjMBAvHhGUcUiF3EscGhenv42UxL7f3tWbsITBNGZg==";
      };
    };
    "volar-service-pug-0.0.68" = {
      name = "volar-service-pug";
      packageName = "volar-service-pug";
      version = "0.0.68";
      src = fetchurl {
        url = "https://registry.npmjs.org/volar-service-pug/-/volar-service-pug-0.0.68.tgz";
        sha512 = "/nZ8fYKDDrV/fqlBoMACWaghFfaIFZMH+qO9YiRsdGbekAvSZqjQAKl1DSJwWqAkabA68Md51mRIdzYzqleipQ==";
      };
    };
    "volar-service-pug-beautify-0.0.68" = {
      name = "volar-service-pug-beautify";
      packageName = "volar-service-pug-beautify";
      version = "0.0.68";
      src = fetchurl {
        url = "https://registry.npmjs.org/volar-service-pug-beautify/-/volar-service-pug-beautify-0.0.68.tgz";
        sha512 = "CUKfD2l9aPam7jeZT0bQtAOfSWm6XmOmTXOfYDMILuK6+5uYiMKbPW2y+OdK2FnHjcAC53GnHpUrIbfxojRoFQ==";
      };
    };
    "volar-service-typescript-0.0.68" = {
      name = "volar-service-typescript";
      packageName = "volar-service-typescript";
      version = "0.0.68";
      src = fetchurl {
        url = "https://registry.npmjs.org/volar-service-typescript/-/volar-service-typescript-0.0.68.tgz";
        sha512 = "z7B/7CnJ0+TWWFp/gh2r5/QwMObHNDiQiv4C9pTBNI2Wxuwymd4bjEORzrJ/hJ5Yd5+OzeYK+nFCKevoGEEeKw==";
      };
    };
    "vscode-css-languageservice-6.3.9" = {
      name = "vscode-css-languageservice";
      packageName = "vscode-css-languageservice";
      version = "6.3.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-css-languageservice/-/vscode-css-languageservice-6.3.9.tgz";
        sha512 = "1tLWfp+TDM5ZuVWht3jmaY5y7O6aZmpeXLoHl5bv1QtRsRKt4xYGRMmdJa5Pqx/FTkgRbsna9R+Gn2xE+evVuA==";
      };
    };
    "vscode-html-languageservice-5.6.1" = {
      name = "vscode-html-languageservice";
      packageName = "vscode-html-languageservice";
      version = "5.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-html-languageservice/-/vscode-html-languageservice-5.6.1.tgz";
        sha512 = "5Mrqy5CLfFZUgkyhNZLA1Ye5g12Cb/v6VM7SxUzZUaRKWMDz4md+y26PrfRTSU0/eQAl3XpO9m2og+GGtDMuaA==";
      };
    };
    "vscode-json-languageservice-5.7.1" = {
      name = "vscode-json-languageservice";
      packageName = "vscode-json-languageservice";
      version = "5.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-json-languageservice/-/vscode-json-languageservice-5.7.1.tgz";
        sha512 = "sMK2F8p7St0lJCr/4IfbQRoEUDUZRR7Ud0IiSl8I/JtN+m9Gv+FJlNkSAYns2R7Ebm/PKxqUuWYOfBej/rAdBQ==";
      };
    };
    "vscode-jsonrpc-8.2.0" = {
      name = "vscode-jsonrpc";
      packageName = "vscode-jsonrpc";
      version = "8.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-8.2.0.tgz";
        sha512 = "C+r0eKJUIfiDIfwJhria30+TYWPtuHJXHtI7J0YlOmKAo7ogxP20T0zxB7HZQIFhIyvoBPwWskjxrvAtfjyZfA==";
      };
    };
    "vscode-languageserver-9.0.1" = {
      name = "vscode-languageserver";
      packageName = "vscode-languageserver";
      version = "9.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver/-/vscode-languageserver-9.0.1.tgz";
        sha512 = "woByF3PDpkHFUreUa7Hos7+pUWdeWMXRd26+ZX2A8cFx6v/JPTtd4/uN0/jB6XQHYaOlHbio03NTHCqrgG5n7g==";
      };
    };
    "vscode-languageserver-protocol-3.17.5" = {
      name = "vscode-languageserver-protocol";
      packageName = "vscode-languageserver-protocol";
      version = "3.17.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-protocol/-/vscode-languageserver-protocol-3.17.5.tgz";
        sha512 = "mb1bvRJN8SVznADSGWM9u/b07H7Ecg0I3OgXDuLdn307rl/J3A9YD6/eYOssqhecL27hK1IPZAsaqh00i/Jljg==";
      };
    };
    "vscode-languageserver-textdocument-1.0.12" = {
      name = "vscode-languageserver-textdocument";
      packageName = "vscode-languageserver-textdocument";
      version = "1.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-textdocument/-/vscode-languageserver-textdocument-1.0.12.tgz";
        sha512 = "cxWNPesCnQCcMPeenjKKsOCKQZ/L6Tv19DTRIGuLWe32lyzWhihGVJ/rcckZXJxfdKCFvRLS3fpBIsV/ZGX4zA==";
      };
    };
    "vscode-languageserver-types-3.17.5" = {
      name = "vscode-languageserver-types";
      packageName = "vscode-languageserver-types";
      version = "3.17.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.17.5.tgz";
        sha512 = "Ld1VelNuX9pdF39h2Hgaeb5hEZM2Z3jUrrMgWQAu82jMtZp7p3vJT3BzToKtZI7NgQssZje5o0zryOrhQvzQAg==";
      };
    };
    "vscode-nls-5.2.0" = {
      name = "vscode-nls";
      packageName = "vscode-nls";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-nls/-/vscode-nls-5.2.0.tgz";
        sha512 = "RAaHx7B14ZU04EU31pT+rKz2/zSl7xMsfIZuo8pd+KZO6PXtQmpevpq3vxvWNcrGbdmhM/rr5Uw5Mz+NBfhVng==";
      };
    };
    "vscode-uri-3.1.0" = {
      name = "vscode-uri";
      packageName = "vscode-uri";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-uri/-/vscode-uri-3.1.0.tgz";
        sha512 = "/BpdSx+yCQGnCvecbyXdxHDkuk55/G3xwnC0GqY4gmQ3j+A+g8kzzgB4Nk/SINjqn6+waqw3EgbVF2QKExkRxQ==";
      };
    };
    "vue-component-meta-3.2.4" = {
      name = "vue-component-meta";
      packageName = "vue-component-meta";
      version = "3.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/vue-component-meta/-/vue-component-meta-3.2.4.tgz";
        sha512 = "FHUxalhR36Kfmrd5B4yfw7kmnCsZL3SGc2vTgzeEGAcLyuhhB0d1j2VmfXvx5pnHLI+kvCb+bxGsRcNgrUJ0Ww==";
      };
    };
    "widest-line-6.0.0" = {
      name = "widest-line";
      packageName = "widest-line";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/widest-line/-/widest-line-6.0.0.tgz";
        sha512 = "U89AsyEeAsyoF0zVJBkG9zBgekjgjK7yk9sje3F4IQpXBJ10TF6ByLlIfjMhcmHMJgHZI4KHt4rdNfktzxIAMA==";
      };
    };
    "wrap-ansi-9.0.2" = {
      name = "wrap-ansi";
      packageName = "wrap-ansi";
      version = "9.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-9.0.2.tgz";
        sha512 = "42AtmgqjV+X1VpdOfyTGOYRi0/zsoLqtXQckTmqTeybT+BDIbM/Guxo7x3pE2vtpr1ok6xRqM9OpBe+Jyoqyww==";
      };
    };
    "ws-7.5.10" = {
      name = "ws";
      packageName = "ws";
      version = "7.5.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-7.5.10.tgz";
        sha512 = "+dbF1tHwZpXcbOJdVOkzLDxZP1ailvSxM6ZweXTegylPny803bFhA+vqBYw4s31NSAk4S2Qz+AKXK9a4wkdjcQ==";
      };
    };
    "ws-8.19.0" = {
      name = "ws";
      packageName = "ws";
      version = "8.19.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-8.19.0.tgz";
        sha512 = "blAT2mjOEIi0ZzruJfIhb3nps74PRWTCz1IjglWEEpQl5XS/UNama6u2/rjFkDDouqr4L67ry+1aGIALViWjDg==";
      };
    };
    "yoga-layout-3.2.1" = {
      name = "yoga-layout";
      packageName = "yoga-layout";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yoga-layout/-/yoga-layout-3.2.1.tgz";
        sha512 = "0LPOt3AxKqMdFBZA3HBAt/t/8vIKq7VaQYbuA8WxCgung+p9TVyKRYdpvCb80HcdTN2NkbIKbhNwKUfm3tQywQ==";
      };
    };
  };
in
{
  "@anthropic-ai/claude-code" = nodeEnv.buildNodePackage {
    name = "_at_anthropic-ai_slash_claude-code";
    packageName = "@anthropic-ai/claude-code";
    version = "2.1.45";
    src = fetchurl {
      url = "https://registry.npmjs.org/@anthropic-ai/claude-code/-/claude-code-2.1.45.tgz";
      sha512 = "L2F7ieThA0MFkzyvA7qhU8s+7pkWTXSQNj6XircdNP+r/L8uhX7JY39NtWpmMvcyxHse+9qUdylGN/rOQgBpXQ==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Use Claude, Anthropic's AI assistant, right from your terminal. Claude can understand your codebase, edit files, run terminal commands, and handle entire workflows for you.";
      homepage = "https://github.com/anthropics/claude-code";
      license = "SEE LICENSE IN README.md";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "@vue/language-server" = nodeEnv.buildNodePackage {
    name = "_at_vue_slash_language-server";
    packageName = "@vue/language-server";
    version = "3.2.4";
    src = fetchurl {
      url = "https://registry.npmjs.org/@vue/language-server/-/language-server-3.2.4.tgz";
      sha512 = "N1/Jx4s+y4xrZpp5uuuFh4v4B330d2jk886pVn3yPYn26f3Vtu8O26P88Y5U2BuLbsmarmJjTYaG3n5gEui6pg==";
    };
    dependencies = [
      sources."@babel/helper-string-parser-7.27.1"
      sources."@babel/helper-validator-identifier-7.28.5"
      sources."@babel/parser-7.29.0"
      sources."@babel/types-7.29.0"
      sources."@emmetio/abbreviation-2.3.3"
      sources."@emmetio/css-abbreviation-2.1.8"
      sources."@emmetio/css-parser-0.4.1"
      sources."@emmetio/html-matcher-1.3.0"
      sources."@emmetio/scanner-1.0.4"
      sources."@emmetio/stream-reader-2.2.0"
      sources."@emmetio/stream-reader-utils-0.1.0"
      sources."@johnsoncodehk/pug-beautify-0.2.2"
      sources."@volar/language-core-2.4.27"
      sources."@volar/language-server-2.4.27"
      sources."@volar/language-service-2.4.27"
      sources."@volar/source-map-2.4.27"
      sources."@volar/typescript-2.4.27"
      sources."@vscode/emmet-helper-2.11.0"
      sources."@vscode/l10n-0.0.18"
      sources."@vue/compiler-core-3.5.28"
      sources."@vue/compiler-dom-3.5.28"
      sources."@vue/language-core-3.2.4"
      sources."@vue/language-service-3.2.4"
      sources."@vue/shared-3.5.28"
      sources."@vue/typescript-plugin-3.2.4"
      sources."acorn-7.4.1"
      sources."alien-signals-3.1.2"
      sources."async-function-1.0.0"
      sources."async-generator-function-1.0.0"
      sources."call-bind-apply-helpers-1.0.2"
      sources."call-bound-1.0.4"
      sources."character-parser-2.2.0"
      sources."dunder-proto-1.0.1"
      sources."emmet-2.4.11"
      sources."entities-7.0.1"
      sources."es-define-property-1.0.1"
      sources."es-errors-1.3.0"
      sources."es-object-atoms-1.1.1"
      sources."estree-walker-2.0.2"
      sources."function-bind-1.1.2"
      sources."generator-function-2.0.1"
      sources."get-intrinsic-1.3.1"
      sources."get-proto-1.0.1"
      sources."gopd-1.2.0"
      sources."has-symbols-1.1.0"
      sources."has-tostringtag-1.0.2"
      sources."hasown-2.0.2"
      sources."is-expression-4.0.0"
      sources."is-regex-1.2.1"
      sources."jsonc-parser-2.3.1"
      sources."math-intrinsics-1.1.0"
      sources."muggle-string-0.4.1"
      sources."object-assign-4.1.1"
      sources."path-browserify-1.0.1"
      sources."picomatch-4.0.3"
      sources."pug-error-2.1.0"
      sources."pug-lexer-5.0.1"
      sources."pug-parser-6.0.0"
      sources."request-light-0.7.0"
      sources."semver-7.7.4"
      sources."source-map-js-1.2.1"
      sources."token-stream-1.0.0"
      sources."typescript-5.9.3"
      sources."typescript-auto-import-cache-0.3.6"
      sources."volar-service-css-0.0.68"
      sources."volar-service-emmet-0.0.68"
      sources."volar-service-html-0.0.68"
      sources."volar-service-json-0.0.68"
      sources."volar-service-pug-0.0.68"
      sources."volar-service-pug-beautify-0.0.68"
      sources."volar-service-typescript-0.0.68"
      sources."vscode-css-languageservice-6.3.9"
      sources."vscode-html-languageservice-5.6.1"
      (sources."vscode-json-languageservice-5.7.1" // {
        dependencies = [
          sources."jsonc-parser-3.3.1"
        ];
      })
      sources."vscode-jsonrpc-8.2.0"
      sources."vscode-languageserver-9.0.1"
      sources."vscode-languageserver-protocol-3.17.5"
      sources."vscode-languageserver-textdocument-1.0.12"
      sources."vscode-languageserver-types-3.17.5"
      sources."vscode-nls-5.2.0"
      sources."vscode-uri-3.1.0"
      sources."vue-component-meta-3.2.4"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      homepage = "https://github.com/vuejs/language-tools#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "@vue/typescript-plugin" = nodeEnv.buildNodePackage {
    name = "_at_vue_slash_typescript-plugin";
    packageName = "@vue/typescript-plugin";
    version = "3.2.4";
    src = fetchurl {
      url = "https://registry.npmjs.org/@vue/typescript-plugin/-/typescript-plugin-3.2.4.tgz";
      sha512 = "K/rKnIQre0X6YyKSbDW+DEYpVkOBrB0ScXus0nvtjI7zwo+0FE+wxUXAXeKtaQwJzQ0d8Pw2FPa0mcZhYpMQug==";
    };
    dependencies = [
      sources."@babel/helper-string-parser-7.27.1"
      sources."@babel/helper-validator-identifier-7.28.5"
      sources."@babel/parser-7.29.0"
      sources."@babel/types-7.29.0"
      sources."@volar/language-core-2.4.27"
      sources."@volar/source-map-2.4.27"
      sources."@volar/typescript-2.4.27"
      sources."@vue/compiler-core-3.5.28"
      sources."@vue/compiler-dom-3.5.28"
      sources."@vue/language-core-3.2.4"
      sources."@vue/shared-3.5.28"
      sources."alien-signals-3.1.2"
      sources."entities-7.0.1"
      sources."estree-walker-2.0.2"
      sources."muggle-string-0.4.1"
      sources."path-browserify-1.0.1"
      sources."picomatch-4.0.3"
      sources."source-map-js-1.2.1"
      sources."typescript-5.9.3"
      sources."vscode-uri-3.1.0"
      sources."vue-component-meta-3.2.4"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "This is a plug-in for `tsserver` or `typescript-language-server`. It must be installed in a file-system location accessible by the language server or in the `node_modules` directory of projects being edited.";
      homepage = "https://github.com/vuejs/language-tools#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  ccmanager = nodeEnv.buildNodePackage {
    name = "ccmanager";
    packageName = "ccmanager";
    version = "3.8.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/ccmanager/-/ccmanager-3.8.1.tgz";
      sha512 = "ljZixAic7Siw/CQWyATTl9II4h3mDAFR8Lxgj2qu33n7HrUH1zWWXgC2bdZjbl+vjzhMauyJOPixGgbSZrhIBg==";
    };
    dependencies = [
      sources."@alcalzone/ansi-tokenize-0.2.5"
      sources."@standard-schema/spec-1.1.0"
      sources."@types/react-19.2.14"
      sources."@xterm/headless-6.0.0"
      sources."ansi-escapes-7.3.0"
      sources."ansi-regex-6.2.2"
      sources."ansi-styles-6.2.3"
      sources."auto-bind-5.0.1"
      sources."bufferutil-4.1.0"
      sources."chalk-5.6.2"
      sources."cli-boxes-3.0.0"
      sources."cli-cursor-4.0.0"
      sources."cli-truncate-5.1.1"
      sources."code-excerpt-4.0.0"
      sources."convert-to-spaces-2.0.1"
      sources."csstype-3.2.3"
      sources."effect-3.19.18"
      sources."emoji-regex-10.6.0"
      sources."environment-1.1.0"
      sources."es-toolkit-1.44.0"
      sources."escape-string-regexp-2.0.0"
      sources."fast-check-3.23.2"
      sources."figures-6.1.0"
      sources."get-east-asian-width-1.4.0"
      sources."indent-string-5.0.0"
      sources."ink-6.7.0"
      sources."ink-select-input-6.2.0"
      (sources."ink-text-input-6.0.0" // {
        dependencies = [
          sources."type-fest-4.41.0"
        ];
      })
      sources."is-fullwidth-code-point-5.1.0"
      sources."is-in-ci-2.0.0"
      sources."is-unicode-supported-2.1.0"
      sources."meow-14.0.0"
      sources."mimic-fn-2.1.0"
      sources."node-gyp-build-4.8.4"
      sources."onetime-5.1.2"
      sources."patch-console-2.0.0"
      sources."pure-rand-6.1.0"
      sources."react-19.2.4"
      (sources."react-devtools-core-6.1.5" // {
        dependencies = [
          sources."utf-8-validate-5.0.10"
          sources."ws-7.5.10"
        ];
      })
      sources."react-dom-19.2.4"
      sources."react-reconciler-0.33.0"
      sources."restore-cursor-4.0.0"
      sources."scheduler-0.27.0"
      sources."shell-quote-1.8.3"
      sources."signal-exit-3.0.7"
      sources."slice-ansi-7.1.2"
      sources."stack-utils-2.0.6"
      sources."string-width-8.1.1"
      sources."strip-ansi-7.1.2"
      sources."tagged-tag-1.0.0"
      sources."terminal-size-4.0.1"
      sources."to-rotated-1.0.0"
      sources."type-fest-5.4.4"
      sources."utf-8-validate-6.0.6"
      sources."widest-line-6.0.0"
      (sources."wrap-ansi-9.0.2" // {
        dependencies = [
          sources."string-width-7.2.0"
        ];
      })
      sources."ws-8.19.0"
      sources."yoga-layout-3.2.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "TUI application for managing multiple Claude Code sessions across Git worktrees";
      homepage = "https://github.com/kbwo/ccmanager#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
