# This file has been generated by node2nix 1.11.0. Do not edit!

{pkgs ? import <nixpkgs> {
    inherit system;
  }, system ? builtins.currentSystem, nodejs ? pkgs.nodejs_22}:

let
  # nodejs_22 is a symlink wrapper that includes npm but lacks .src.
  # Provide nodejs-slim source so native addons can compile.
  nodejsWithSrc = nodejs // { src = pkgs.nodejs-slim_22.src; };
  nodeEnv = import ./node-env.nix {
    inherit (pkgs) stdenv lib runCommand writeTextFile writeShellScript;
    inherit pkgs;
    nodejs = nodejsWithSrc;
    python2 = pkgs.python3;
    libtool = if pkgs.stdenv.isDarwin then pkgs.darwin.cctools else null;
  };
in
import ./node-packages.nix {
  inherit (pkgs) fetchurl nix-gitignore stdenv lib fetchgit;
  inherit nodeEnv;
}
