[package]
name = "mikinovation-api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "=0.8.3"
tokio = { version = "=1.44.2", features = ["full"] }
sqlx = { version = "=0.8.5", features = [
	"runtime-tokio",
	"tls-rustls",
	"sqlite",
	"macros",
	"chrono"
] }
serde = { version = "=1.0.219", features = ["derive"] }
serde_json = "=1.0.140"
time = "=0.3.41"
tower-http = { version = "=0.6.2", features = ["trace", "cors"] }
tracing = "=0.1.41"
tracing-subscriber = { version = "=0.3.19", features = ["env-filter"] }
chrono = { version = "=0.4.40", features = ["serde"] }
uuid = { version = "=1.16.0", features = ["v4", "serde"] }
thiserror = "=2.0.12"
anyhow = "=1.0.98"
async-trait = "=0.1.88"
