[package]
name = "mikinovation-api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "=0.8.4"
tokio = { version = "=1.45.0", features = ["full"] }
sqlx = { version = "=0.8.6", features = [
	"runtime-tokio",
	"tls-rustls",
	"postgres",
	"macros",
	"chrono",
	"uuid"
] }
serde = { version = "=1.0.219", features = ["derive"] }
serde_json = "=1.0.140"
time = "=0.3.41"
tower-http = { version = "=0.6.4", features = ["trace", "cors"] }
tracing = "=0.1.41"
tracing-subscriber = { version = "=0.3.19", features = ["env-filter"] }
chrono = { version = "=0.4.41", features = ["serde"] }
uuid = { version = "=1.17.0", features = ["v4", "serde"] }
thiserror = "=2.0.12"
anyhow = "=1.0.98"
async-trait = "=0.1.88"
oauth2 = "=5.0.0"
reqwest = { version = "=0.12.14", features = ["json"] }
jsonwebtoken = "=9.3.0"
rand = "=0.8.5"
base64 = "=0.22.1"
reqwest-middleware = "0.4.2"
