services:
  postgres:
    image: postgres:17.5
    container_name: mikinovation_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mikinovation
      TZ: Asia/Tokyo
      PGTZ: Asia/Tokyo
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
